# 1) Importing Libraries and DataFrame

In [1]:
# Importing libraries

import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt 
import seaborn as sns
from datetime import datetime

In [2]:
# Importing dataframe dated 04/22

path = r'/Users/matthewabrams'
bikes_04 = pd.read_csv(os.path.join(path, 'Downloads', '202204-citibike-tripdata.csv'), index_col = False)
bikes_04

/Users/matthewabrams/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (5,7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,2E89F1D88B8347E6,classic_bike,2022-04-08 19:50:00,2022-04-08 19:55:28,E 89 St & 3 Ave,7265.10,Madison Ave & E 99 St,7443.01,40.780628,-73.952167,40.789485,-73.952429,member
1,43F6D61DFEDAE4AF,electric_bike,2022-04-27 10:19:54,2022-04-27 10:33:29,Broadway & W 29 St,6289.06,Broadway & W 29 St,6289.06,40.746201,-73.988557,40.746201,-73.988557,member
2,21C7076071104314,classic_bike,2022-04-28 13:10:59,2022-04-28 13:17:18,E 123 St & Lexington Ave,7636.05,E 123 St & Lexington Ave,7636.05,40.802926,-73.937900,40.802926,-73.937900,member
3,7D7CEA2953427D0C,classic_bike,2022-04-13 20:21:18,2022-04-13 20:37:28,W 36 St & 9 Ave,6569.07,W 36 St & 9 Ave,6569.07,40.754623,-73.995168,40.754623,-73.995168,member
4,AD7E176748A4A55E,electric_bike,2022-04-29 18:56:24,2022-04-29 18:57:16,Graham Ave & Withers St,5403.04,Graham Ave & Withers St,5403.04,40.716981,-73.944859,40.716981,-73.944859,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2319608,5EBE9D296B9D3E3C,classic_bike,2022-04-22 13:08:15,2022-04-22 13:29:31,Allen St & Rivington St,5414.06,W 29 St & 9 Ave,6416.06,40.720196,-73.989978,40.750073,-73.998393,member
2319609,B66382DEDA84C464,classic_bike,2022-04-13 17:10:49,2022-04-13 17:26:08,St. Nicholas Terrace & Convent Ave,7937.15,E 138 St & Grand Concourse,7803.08,40.821294,-73.947868,40.813224,-73.930605,member
2319610,9EC4C49BE4CB1A09,classic_bike,2022-04-12 15:58:47,2022-04-12 16:41:17,E 88 St & 1 Ave,7235.13,E 91 St & 2 Ave,7286.01,40.778301,-73.948813,40.781153,-73.949630,member
2319611,C0188AB9FAEAA143,electric_bike,2022-04-28 15:52:49,2022-04-28 16:06:31,W 55 St & 6 Ave,6809.09,E 91 St & 2 Ave,7286.01,40.763189,-73.978434,40.781153,-73.949630,member
2319612,E8C2F305866DF134,electric_bike,2022-04-11 19:55:31,2022-04-11 20:09:19,W 87 St & West End Ave,7484.05,E 91 St & 2 Ave,7286.01,40.789622,-73.977570,40.781153,-73.949630,member

In [3]:
# Importing dataframe dated 03/22

bikes_03 = pd.read_csv(os.path.join(path, 'Downloads', '202203-citibike-tripdata.csv'), index_col = False)
bikes_03

/Users/matthewabrams/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (5,7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,FA2F660C8D433037,electric_bike,2022-03-04 18:58:36,2022-03-04 19:13:51,Washington St & Barrow St,5847.08,University Pl & E 14 St,5905.14,40.731911,-74.008769,40.734814,-73.992085,member
1,03B6FE6FAEE61465,classic_bike,2022-03-06 20:37:09,2022-03-06 20:45:28,Washington St & Barrow St,5847.08,W 11 St & 6 Ave,5914.03,40.731911,-74.008769,40.735324,-73.998004,member
2,6E6995761B4A5760,classic_bike,2022-03-01 15:13:49,2022-03-01 15:19:53,1 Ave & E 110 St,7522.02,E 110 St & Madison Ave,7587.14,40.792327,-73.938300,40.796154,-73.947821,member
3,AA51CCF6CEDD6033,classic_bike,2022-03-11 13:59:03,2022-03-11 14:06:43,Crescent St & Broadway,6827.11,31 Rd & 21 St,6929.02,40.763359,-73.928647,40.766824,-73.930486,member
4,72AA3A7D430D8EF8,classic_bike,2022-03-08 14:59:16,2022-03-08 15:05:04,Crescent St & Broadway,6827.11,31 Rd & 21 St,6929.02,40.763359,-73.928647,40.766824,-73.930486,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1893439,79E49EA8727CA662,classic_bike,2022-03-30 21:12:45,2022-03-30 21:22:15,E 72 St & York Ave,6889.12,E 58 St & 3 Ave,6762.02,40.766638,-73.953483,40.760958,-73.967245,member
1893440,9C4F6A095779AAE2,electric_bike,2022-03-21 09:33:21,2022-03-21 09:39:45,W 48 St & Rockefeller Plaza,6626.11,E 58 St & 3 Ave,6762.02,40.757769,-73.979294,40.760958,-73.967245,member
1893441,C1966A89B5078124,electric_bike,2022-03-04 14:31:36,2022-03-04 14:43:16,Central Park West & W 85 St,7354.01,E 58 St & 3 Ave,6762.02,40.784760,-73.969862,40.760958,-73.967245,member
1893442,A11D1F167EF1B8C6,classic_bike,2022-03-18 18:43:43,2022-03-18 18:53:41,W 56 St & 6 Ave,6809.07,E 58 St & 3 Ave,6762.02,40.763406,-73.977225,40.760958,-73.967245,member
1893443,74A6A40E386BE88F,electric_bike,2022-03-10 17:21:52,2022-03-10 17:29:53,5 Ave & E 72 St,7100.07,E 58 St & 3 Ave,6762.02,40.772828,-73.966853,40.760958,-73.967245,casual

In [4]:
# Importing dataframe dated 02/22

bikes_02 = pd.read_csv(os.path.join(path, 'Downloads', '202202-citibike-tripdata.csv'), index_col = False)
bikes_02

/Users/matthewabrams/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (5,7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,6C29577D0141AACD,electric_bike,2022-02-27 16:00:58,2022-02-27 16:10:09,Cliff St & Fulton St,5065.14,Norfolk St & Broome St,5374.01,40.708380,-74.004950,40.717227,-73.988021,member
1,353462A61AFB32C8,classic_bike,2022-02-02 18:09:30,2022-02-02 18:28:55,2 Ave & E 31 St,6197.02,Norfolk St & Broome St,5374.01,40.742909,-73.977061,40.717227,-73.988021,member
2,220081222C7CC84D,classic_bike,2022-02-10 19:41:09,2022-02-10 19:46:03,2 Ave & E 31 St,6197.02,5 Ave & E 29 St,6248.06,40.742909,-73.977061,40.745168,-73.986831,member
3,C66CB5EDE74A7404,classic_bike,2022-02-14 15:52:02,2022-02-14 16:01:58,Bridge St & Water St,4968.03,Henry St & Atlantic Ave,4531.05,40.702969,-73.984691,40.690893,-73.996123,member
4,6B997C1E4DCDD6BF,classic_bike,2022-02-23 13:25:07,2022-02-23 15:36:45,Lafayette St & Jersey St,5561.06,Fulton St & Broadway,5175.08,40.724561,-73.995653,40.711066,-74.009447,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1233709,DB7E2CCB36FE2470,classic_bike,2022-02-02 20:20:40,2022-02-02 20:32:36,Columbus Ave & W 95 St,7520.07,E 110 St & Madison Ave,7587.14,40.791956,-73.968087,40.796154,-73.947821,member
1233710,2589BCEF3734CEFA,electric_bike,2022-02-12 18:21:44,2022-02-12 18:30:48,Central Park West & W 85 St,7354.01,E 110 St & Madison Ave,7587.14,40.784760,-73.969862,40.796154,-73.947821,member
1233711,D808B985BB9F9D72,classic_bike,2022-02-26 12:58:46,2022-02-26 13:11:58,Stanton St & Mangin St,5326.06,E 10 St & 2 Ave,5746.02,40.717821,-73.976289,40.729708,-73.986598,casual
1233712,F3CBF555F8561BF0,electric_bike,2022-02-18 11:03:02,2022-02-18 11:06:01,E 11 St & 3 Ave,5788.16,E 10 St & 2 Ave,5746.02,40.731270,-73.988490,40.729708,-73.986598,casual
1233713,2F8F2920C1A9D0E8,electric_bike,2022-02-19 18:11:55,2022-02-19 18:38:39,E 33 St & 5 Ave,6322.01,Mott St & Prince St,5561.04,40.747659,-73.984907,40.723180,-73.994800,casual

In [5]:
# Importing dataframe dated 01/22

bikes_01 = pd.read_csv(os.path.join(path, 'Downloads', '202201-citibike-tripdata.csv'), index_col = False)
bikes_01

/Users/matthewabrams/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (5,7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,40.692395,-73.993379,member
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,40.727408,-73.981420,member
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,40.762009,-73.996975,member
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,40.768692,-73.924957,member
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,40.696233,-73.991421,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1052413,3A8436E896501EB6,classic_bike,2022-01-09 09:40:49,2022-01-09 09:58:55,27 St & Hunter St,6310.06,Vernon Blvd & 50 Ave,6170.02,40.748500,-73.941275,40.742327,-73.954117,casual
1052414,31EE3AF319AE47D2,classic_bike,2022-01-26 16:11:27,2022-01-26 16:17:20,Monroe St & Bedford Ave,4368.05,Putnam Ave & Throop Ave,4392.04,40.685144,-73.953809,40.685153,-73.941110,casual
1052415,C27D809EC458BE2A,electric_bike,2022-01-20 11:39:41,2022-01-20 11:44:46,E 118 St & 1 Ave,7596.1,Lexington Ave & E 111 St,7567.06,40.797470,-73.935040,40.795412,-73.944123,member
1052416,4968572973DEDCB2,electric_bike,2022-01-18 21:17:11,2022-01-18 21:25:57,Allen St & Hester St,5342.1,1 Ave & E 18 St,5854.09,40.716059,-73.991908,40.733812,-73.980544,member
1052417,B40238814400C8B2,classic_bike,2022-01-22 19:05:54,2022-01-22 19:16:39,Gansevoort St & Hudson St,6072.14,12 Ave & W 40 St,6765.01,40.739448,-74.005070,40.760875,-74.002777,member

In [6]:
# Getting data types of each column for dataframe dated 04/22

bikes_04.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [7]:
# Getting data types of each column for dataframe dated 03/22

bikes_03.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [8]:
# Getting data types of each column for dataframe dated 02/22

bikes_02.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [9]:
# Getting data types of each column for dataframe dated 01/22

bikes_01.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

# 2) Combining Dataframes

In [10]:
# Combining all 4 dataframes using concat method

frames = [bikes_01, bikes_02, bikes_03, bikes_04]
bikes = pd.concat(frames, axis = 0)
bikes

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,40.692395,-73.993379,member
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,40.727408,-73.981420,member
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,40.762009,-73.996975,member
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,40.768692,-73.924957,member
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,40.696233,-73.991421,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2319608,5EBE9D296B9D3E3C,classic_bike,2022-04-22 13:08:15,2022-04-22 13:29:31,Allen St & Rivington St,5414.06,W 29 St & 9 Ave,6416.06,40.720196,-73.989978,40.750073,-73.998393,member
2319609,B66382DEDA84C464,classic_bike,2022-04-13 17:10:49,2022-04-13 17:26:08,St. Nicholas Terrace & Convent Ave,7937.15,E 138 St & Grand Concourse,7803.08,40.821294,-73.947868,40.813224,-73.930605,member
2319610,9EC4C49BE4CB1A09,classic_bike,2022-04-12 15:58:47,2022-04-12 16:41:17,E 88 St & 1 Ave,7235.13,E 91 St & 2 Ave,7286.01,40.778301,-73.948813,40.781153,-73.949630,member
2319611,C0188AB9FAEAA143,electric_bike,2022-04-28 15:52:49,2022-04-28 16:06:31,W 55 St & 6 Ave,6809.09,E 91 St & 2 Ave,7286.01,40.763189,-73.978434,40.781153,-73.949630,member
2319612,E8C2F305866DF134,electric_bike,2022-04-11 19:55:31,2022-04-11 20:09:19,W 87 St & West End Ave,7484.05,E 91 St & 2 Ave,7286.01,40.789622,-73.977570,40.781153,-73.949630,member

# 3) Checking for missing values, duplicates, and inconsistant values

In [11]:
# Checking for null values

bikes.isnull().sum()

ride_id                   0
rideable_type             0
started_at                0
ended_at                  0
start_station_name        8
start_station_id          8
end_station_name      15750
end_station_id        15750
start_lat                 0
start_lng                 0
end_lat               11573
end_lng               11573
member_casual             0
dtype: int64

In [12]:
# Dropping null values under'start_station_name','end_station_name'
# Want to return all known values for where people bike from and where to

bikes.dropna(subset = ['start_station_name','end_station_name'], inplace = True)
bikes

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,40.692395,-73.993379,member
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,40.727408,-73.981420,member
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,40.762009,-73.996975,member
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,40.768692,-73.924957,member
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,40.696233,-73.991421,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2319608,5EBE9D296B9D3E3C,classic_bike,2022-04-22 13:08:15,2022-04-22 13:29:31,Allen St & Rivington St,5414.06,W 29 St & 9 Ave,6416.06,40.720196,-73.989978,40.750073,-73.998393,member
2319609,B66382DEDA84C464,classic_bike,2022-04-13 17:10:49,2022-04-13 17:26:08,St. Nicholas Terrace & Convent Ave,7937.15,E 138 St & Grand Concourse,7803.08,40.821294,-73.947868,40.813224,-73.930605,member
2319610,9EC4C49BE4CB1A09,classic_bike,2022-04-12 15:58:47,2022-04-12 16:41:17,E 88 St & 1 Ave,7235.13,E 91 St & 2 Ave,7286.01,40.778301,-73.948813,40.781153,-73.949630,member
2319611,C0188AB9FAEAA143,electric_bike,2022-04-28 15:52:49,2022-04-28 16:06:31,W 55 St & 6 Ave,6809.09,E 91 St & 2 Ave,7286.01,40.763189,-73.978434,40.781153,-73.949630,member
2319612,E8C2F305866DF134,electric_bike,2022-04-11 19:55:31,2022-04-11 20:09:19,W 87 St & West End Ave,7484.05,E 91 St & 2 Ave,7286.01,40.789622,-73.977570,40.781153,-73.949630,member

In [13]:
# Checking for duplicates
# No duplicates

bikes[bikes.duplicated()]

Empty DataFrame
Columns: [ride_id, rideable_type, started_at, ended_at, start_station_name, start_station_id, end_station_name, end_station_id, start_lat, start_lng, end_lat, end_lng, member_casual]
Index: []

In [14]:
bikes['start_station_name'].value_counts()

W 21 St & 6 Ave          30302
1 Ave & E 68 St          27128
Broadway & W 58 St       25466
Broadway & E 21 St       25045
West St & Chambers St    24004
                         ...
Folin St & E 181 St         15
Morgan WH station            9
E 6 St 2 Ave                 7
Morgan Loading Docks         3
Morgan Bike Mechanics        1
Name: start_station_name, Length: 1563, dtype: int64

In [15]:
bikes['end_station_name'].value_counts()

W 21 St & 6 Ave            30542
1 Ave & E 68 St            27060
Broadway & E 21 St         25197
Broadway & W 58 St         25118
University Pl & E 14 St    24570
                           ...
Monmouth and 6th               1
StuyTown Depot                 1
Grove St PATH                  1
Manila & 1st                   1
Astor Place                    1
Name: end_station_name, Length: 1605, dtype: int64

In [16]:
# Finding how many types of ridable bikes there are
# There are three types of rideable bikes

bikes['rideable_type'].unique()

array(['classic_bike', 'electric_bike', 'docked_bike'], dtype=object)

In [17]:
bikes['member_casual'].unique()

array(['member', 'casual'], dtype=object)

# 4) Changing datatypes and adding new columns

In [18]:
# Changing datatype of column from object to datestamp

bikes['started_at'] = pd.to_datetime(bikes['started_at'])

In [19]:
# Changing datatype of column from object to datestamp

bikes['ended_at'] = pd.to_datetime(bikes['ended_at'])

In [20]:
# Checking for changes made in datatypes of each column

bikes.dtypes

ride_id                       object
rideable_type                 object
started_at            datetime64[ns]
ended_at              datetime64[ns]
start_station_name            object
start_station_id              object
end_station_name              object
end_station_id                object
start_lat                    float64
start_lng                    float64
end_lat                      float64
end_lng                      float64
member_casual                 object
dtype: object

In [21]:
# Creating column for how much time spent on bike ride, labeled "time_spent_with_bike"
# Formula was derived from taking the difference between "ended_at" and "started_at" column

bikes["time_spent_with_bike"] = bikes['ended_at'] - bikes['started_at']
bikes

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,time_spent_with_bike
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,40.692395,-73.993379,member,0 days 00:04:26
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,40.727408,-73.981420,member,0 days 00:02:22
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,40.762009,-73.996975,member,0 days 00:24:46
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,40.768692,-73.924957,member,0 days 00:04:15
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,40.696233,-73.991421,member,0 days 00:08:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2319608,5EBE9D296B9D3E3C,classic_bike,2022-04-22 13:08:15,2022-04-22 13:29:31,Allen St & Rivington St,5414.06,W 29 St & 9 Ave,6416.06,40.720196,-73.989978,40.750073,-73.998393,member,0 days 00:21:16
2319609,B66382DEDA84C464,classic_bike,2022-04-13 17:10:49,2022-04-13 17:26:08,St. Nicholas Terrace & Convent Ave,7937.15,E 138 St & Grand Concourse,7803.08,40.821294,-73.947868,40.813224,-73.930605,member,0 days 00:15:19
2319610,9EC4C49BE4CB1A09,classic_bike,2022-04-12 15:58:47,2022-04-12 16:41:17,E 88 St & 1 Ave,7235.13,E 91 St & 2 Ave,7286.01,40.778301,-73.948813,40.781153,-73.949630,member,0 days 00:42:30
2319611,C0188AB9FAEAA143,electric_bike,2022-04-28 15:52:49,2022-04-28 16:06:31,W 55 St & 6 Ave,6809.09,E 91 St & 2 Ave,7286.01,40.763189,-73.978434,40.781153,-73.949630,member,0 days 00:13:42
2319612,E8C2F305866DF134,electric_bike,2022-04-11 19:55:31,2022-04-11 20:09:19,W 87 St & West End Ave,7484.05,E 91 St & 2 Ave,7286.01,40.789622,-73.977570,40.781153,-73.949630,member,0 days 00:13:48

In [22]:
# Changed data type of 'time_spent_with_bike' column to an integer and also converted time spent to total seconds

bikes['time_spent_with_bike'] = bikes['time_spent_with_bike'].dt.total_seconds().astype(int)
bikes

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,time_spent_with_bike
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,40.692395,-73.993379,member,266
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,40.727408,-73.981420,member,142
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,40.762009,-73.996975,member,1486
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,40.768692,-73.924957,member,255
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,40.696233,-73.991421,member,480
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2319608,5EBE9D296B9D3E3C,classic_bike,2022-04-22 13:08:15,2022-04-22 13:29:31,Allen St & Rivington St,5414.06,W 29 St & 9 Ave,6416.06,40.720196,-73.989978,40.750073,-73.998393,member,1276
2319609,B66382DEDA84C464,classic_bike,2022-04-13 17:10:49,2022-04-13 17:26:08,St. Nicholas Terrace & Convent Ave,7937.15,E 138 St & Grand Concourse,7803.08,40.821294,-73.947868,40.813224,-73.930605,member,919
2319610,9EC4C49BE4CB1A09,classic_bike,2022-04-12 15:58:47,2022-04-12 16:41:17,E 88 St & 1 Ave,7235.13,E 91 St & 2 Ave,7286.01,40.778301,-73.948813,40.781153,-73.949630,member,2550
2319611,C0188AB9FAEAA143,electric_bike,2022-04-28 15:52:49,2022-04-28 16:06:31,W 55 St & 6 Ave,6809.09,E 91 St & 2 Ave,7286.01,40.763189,-73.978434,40.781153,-73.949630,member,822
2319612,E8C2F305866DF134,electric_bike,2022-04-11 19:55:31,2022-04-11 20:09:19,W 87 St & West End Ave,7484.05,E 91 St & 2 Ave,7286.01,40.789622,-73.977570,40.781153,-73.949630,member,828

In [23]:
# Created new column derived from 'time_spent_with_bike'
# Converted time spent from total seconds to minutes (nearest two places after decimal)

bikes['time_spent_with_bike_in_minutes'] = round((bikes['time_spent_with_bike']/60),2)
bikes

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,time_spent_with_bike,time_spent_with_bike_in_minutes
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,40.692395,-73.993379,member,266,4.43
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,40.727408,-73.981420,member,142,2.37
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,40.762009,-73.996975,member,1486,24.77
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,40.768692,-73.924957,member,255,4.25
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,40.696233,-73.991421,member,480,8.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2319608,5EBE9D296B9D3E3C,classic_bike,2022-04-22 13:08:15,2022-04-22 13:29:31,Allen St & Rivington St,5414.06,W 29 St & 9 Ave,6416.06,40.720196,-73.989978,40.750073,-73.998393,member,1276,21.27
2319609,B66382DEDA84C464,classic_bike,2022-04-13 17:10:49,2022-04-13 17:26:08,St. Nicholas Terrace & Convent Ave,7937.15,E 138 St & Grand Concourse,7803.08,40.821294,-73.947868,40.813224,-73.930605,member,919,15.32
2319610,9EC4C49BE4CB1A09,classic_bike,2022-04-12 15:58:47,2022-04-12 16:41:17,E 88 St & 1 Ave,7235.13,E 91 St & 2 Ave,7286.01,40.778301,-73.948813,40.781153,-73.949630,member,2550,42.50
2319611,C0188AB9FAEAA143,electric_bike,2022-04-28 15:52:49,2022-04-28 16:06:31,W 55 St & 6 Ave,6809.09,E 91 St & 2 Ave,7286.01,40.763189,-73.978434,40.781153,-73.949630,member,822,13.70
2319612,E8C2F305866DF134,electric_bike,2022-04-11 19:55:31,2022-04-11 20:09:19,W 87 St & West End Ave,7484.05,E 91 St & 2 Ave,7286.01,40.789622,-73.977570,40.781153,-73.949630,member,828,13.80

In [24]:
# Created two new columns derived from 'ended_at_day_name', 'started_at_day_name'
# Returned the name of day

bikes['started_at_day_name'] = bikes['started_at'].dt.day_name()
bikes['ended_at_day_name'] = bikes['ended_at'].dt.day_name()
bikes

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,time_spent_with_bike,time_spent_with_bike_in_minutes,started_at_day_name,ended_at_day_name
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,40.692395,-73.993379,member,266,4.43,Tuesday,Tuesday
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,40.727408,-73.981420,member,142,2.37,Friday,Friday
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,40.762009,-73.996975,member,1486,24.77,Saturday,Saturday
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,40.768692,-73.924957,member,255,4.25,Wednesday,Wednesday
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,40.696233,-73.991421,member,480,8.00,Sunday,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2319608,5EBE9D296B9D3E3C,classic_bike,2022-04-22 13:08:15,2022-04-22 13:29:31,Allen St & Rivington St,5414.06,W 29 St & 9 Ave,6416.06,40.720196,-73.989978,40.750073,-73.998393,member,1276,21.27,Friday,Friday
2319609,B66382DEDA84C464,classic_bike,2022-04-13 17:10:49,2022-04-13 17:26:08,St. Nicholas Terrace & Convent Ave,7937.15,E 138 St & Grand Concourse,7803.08,40.821294,-73.947868,40.813224,-73.930605,member,919,15.32,Wednesday,Wednesday
2319610,9EC4C49BE4CB1A09,classic_bike,2022-04-12 15:58:47,2022-04-12 16:41:17,E 88 St & 1 Ave,7235.13,E 91 St & 2 Ave,7286.01,40.778301,-73.948813,40.781153,-73.949630,member,2550,42.50,Tuesday,Tuesday
2319611,C0188AB9FAEAA143,electric_bike,2022-04-28 15:52:49,2022-04-28 16:06:31,W 55 St & 6 Ave,6809.09,E 91 St & 2 Ave,7286.01,40.763189,-73.978434,40.781153,-73.949630,member,822,13.70,Thursday,Thursday
2319612,E8C2F305866DF134,electric_bike,2022-04-11 19:55:31,2022-04-11 20:09:19,W 87 St & West End Ave,7484.05,E 91 St & 2 Ave,7286.01,40.789622,-73.977570,40.781153,-73.949630,member,828,13.80,Monday,Monday

In [25]:
# Created two new columns derived from 'ended_at_day_name', 'started_at_day_name'
# Returned the hour of day

bikes['started_at_hour'] = bikes['started_at'].dt.hour
bikes['ended_at_hour'] = bikes['ended_at'].dt.hour
bikes

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,time_spent_with_bike,time_spent_with_bike_in_minutes,started_at_day_name,ended_at_day_name,started_at_hour,ended_at_hour
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,40.692395,-73.993379,member,266,4.43,Tuesday,Tuesday,8,8
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,40.727408,-73.981420,member,142,2.37,Friday,Friday,9,9
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,40.762009,-73.996975,member,1486,24.77,Saturday,Saturday,14,14
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,40.768692,-73.924957,member,255,4.25,Wednesday,Wednesday,14,14
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,40.696233,-73.991421,member,480,8.00,Sunday,Sunday,14,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2319608,5EBE9D296B9D3E3C,classic_bike,2022-04-22 13:08:15,2022-04-22 13:29:31,Allen St & Rivington St,5414.06,W 29 St & 9 Ave,6416.06,40.720196,-73.989978,40.750073,-73.998393,member,1276,21.27,Friday,Friday,13,13
2319609,B66382DEDA84C464,classic_bike,2022-04-13 17:10:49,2022-04-13 17:26:08,St. Nicholas Terrace & Convent Ave,7937.15,E 138 St & Grand Concourse,7803.08,40.821294,-73.947868,40.813224,-73.930605,member,919,15.32,Wednesday,Wednesday,17,17
2319610,9EC4C49BE4CB1A09,classic_bike,2022-04-12 15:58:47,2022-04-12 16:41:17,E 88 St & 1 Ave,7235.13,E 91 St & 2 Ave,7286.01,40.778301,-73.948813,40.781153,-73.949630,member,2550,42.50,Tuesday,Tuesday,15,16
2319611,C0188AB9FAEAA143,electric_bike,2022-04-28 15:52:49,2022-04-28 16:06:31,W 55 St & 6 Ave,6809.09,E 91 St & 2 Ave,7286.01,40.763189,-73.978434,40.781153,-73.949630,member,822,13.70,Thursday,Thursday,15,16
2319612,E8C2F305866DF134,electric_bike,2022-04-11 19:55:31,2022-04-11 20:09:19,W 87 St & West End Ave,7484.05,E 91 St & 2 Ave,7286.01,40.789622,-73.977570,40.781153,-73.949630,member,828,13.80,Monday,Monday,19,20

In [26]:
# Created two new columns derived from 'ended_at_day_name', 'started_at_day_name'
# Returned the month of year

bikes['started_at_month_name'] = bikes['started_at'].dt.month_name()
bikes['ended_at_month_name'] = bikes['ended_at'].dt.month_name()

bikes

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,end_lng,member_casual,time_spent_with_bike,time_spent_with_bike_in_minutes,started_at_day_name,ended_at_day_name,started_at_hour,ended_at_hour,started_at_month_name,ended_at_month_name
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,...,-73.993379,member,266,4.43,Tuesday,Tuesday,8,8,January,January
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,...,-73.981420,member,142,2.37,Friday,Friday,9,9,January,January
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,...,-73.996975,member,1486,24.77,Saturday,Saturday,14,14,January,January
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,...,-73.924957,member,255,4.25,Wednesday,Wednesday,14,14,January,January
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,...,-73.991421,member,480,8.00,Sunday,Sunday,14,14,January,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2319608,5EBE9D296B9D3E3C,classic_bike,2022-04-22 13:08:15,2022-04-22 13:29:31,Allen St & Rivington St,5414.06,W 29 St & 9 Ave,6416.06,40.720196,-73.989978,...,-73.998393,member,1276,21.27,Friday,Friday,13,13,April,April
2319609,B66382DEDA84C464,classic_bike,2022-04-13 17:10:49,2022-04-13 17:26:08,St. Nicholas Terrace & Convent Ave,7937.15,E 138 St & Grand Concourse,7803.08,40.821294,-73.947868,...,-73.930605,member,919,15.32,Wednesday,Wednesday,17,17,April,April
2319610,9EC4C49BE4CB1A09,classic_bike,2022-04-12 15:58:47,2022-04-12 16:41:17,E 88 St & 1 Ave,7235.13,E 91 St & 2 Ave,7286.01,40.778301,-73.948813,...,-73.949630,member,2550,42.50,Tuesday,Tuesday,15,16,April,April
2319611,C0188AB9FAEAA143,electric_bike,2022-04-28 15:52:49,2022-04-28 16:06:31,W 55 St & 6 Ave,6809.09,E 91 St & 2 Ave,7286.01,40.763189,-73.978434,...,-73.949630,member,822,13.70,Thursday,Thursday,15,16,April,April
2319612,E8C2F305866DF134,electric_bike,2022-04-11 19:55:31,2022-04-11 20:09:19,W 87 St & West End Ave,7484.05,E 91 St & 2 Ave,7286.01,40.789622,-73.977570,...,-73.949630,member,828,13.80,Monday,Monday,19,20,April,April

In [27]:
# Created two new columns derived from 'ended_at_day_name', 'started_at_day_name'
# Returned the year

bikes['started_at_year'] = bikes['started_at'].dt.year
bikes['ended_at_year'] = bikes['ended_at'].dt.year
bikes

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,time_spent_with_bike,time_spent_with_bike_in_minutes,started_at_day_name,ended_at_day_name,started_at_hour,ended_at_hour,started_at_month_name,ended_at_month_name,started_at_year,ended_at_year
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,...,266,4.43,Tuesday,Tuesday,8,8,January,January,2022,2022
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,...,142,2.37,Friday,Friday,9,9,January,January,2022,2022
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,...,1486,24.77,Saturday,Saturday,14,14,January,January,2022,2022
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,...,255,4.25,Wednesday,Wednesday,14,14,January,January,2022,2022
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,...,480,8.00,Sunday,Sunday,14,14,January,January,2022,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2319608,5EBE9D296B9D3E3C,classic_bike,2022-04-22 13:08:15,2022-04-22 13:29:31,Allen St & Rivington St,5414.06,W 29 St & 9 Ave,6416.06,40.720196,-73.989978,...,1276,21.27,Friday,Friday,13,13,April,April,2022,2022
2319609,B66382DEDA84C464,classic_bike,2022-04-13 17:10:49,2022-04-13 17:26:08,St. Nicholas Terrace & Convent Ave,7937.15,E 138 St & Grand Concourse,7803.08,40.821294,-73.947868,...,919,15.32,Wednesday,Wednesday,17,17,April,April,2022,2022
2319610,9EC4C49BE4CB1A09,classic_bike,2022-04-12 15:58:47,2022-04-12 16:41:17,E 88 St & 1 Ave,7235.13,E 91 St & 2 Ave,7286.01,40.778301,-73.948813,...,2550,42.50,Tuesday,Tuesday,15,16,April,April,2022,2022
2319611,C0188AB9FAEAA143,electric_bike,2022-04-28 15:52:49,2022-04-28 16:06:31,W 55 St & 6 Ave,6809.09,E 91 St & 2 Ave,7286.01,40.763189,-73.978434,...,822,13.70,Thursday,Thursday,15,16,April,April,2022,2022
2319612,E8C2F305866DF134,electric_bike,2022-04-11 19:55:31,2022-04-11 20:09:19,W 87 St & West End Ave,7484.05,E 91 St & 2 Ave,7286.01,40.789622,-73.977570,...,828,13.80,Monday,Monday,19,20,April,April,2022,2022

In [28]:
# Created two new columns derived from 'ended_at_day_name', 'started_at_day_name'
# Returned the year-month-day

bikes['started_at_date'] = bikes['started_at'].dt.to_period('D')
bikes['ended_at_date'] = bikes['ended_at'].dt.to_period('D')
bikes

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,started_at_day_name,ended_at_day_name,started_at_hour,ended_at_hour,started_at_month_name,ended_at_month_name,started_at_year,ended_at_year,started_at_date,ended_at_date
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,...,Tuesday,Tuesday,8,8,January,January,2022,2022,2022-01-18,2022-01-18
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,...,Friday,Friday,9,9,January,January,2022,2022,2022-01-21,2022-01-21
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,...,Saturday,Saturday,14,14,January,January,2022,2022,2022-01-22,2022-01-22
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,...,Wednesday,Wednesday,14,14,January,January,2022,2022,2022-01-19,2022-01-19
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,...,Sunday,Sunday,14,14,January,January,2022,2022,2022-01-16,2022-01-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2319608,5EBE9D296B9D3E3C,classic_bike,2022-04-22 13:08:15,2022-04-22 13:29:31,Allen St & Rivington St,5414.06,W 29 St & 9 Ave,6416.06,40.720196,-73.989978,...,Friday,Friday,13,13,April,April,2022,2022,2022-04-22,2022-04-22
2319609,B66382DEDA84C464,classic_bike,2022-04-13 17:10:49,2022-04-13 17:26:08,St. Nicholas Terrace & Convent Ave,7937.15,E 138 St & Grand Concourse,7803.08,40.821294,-73.947868,...,Wednesday,Wednesday,17,17,April,April,2022,2022,2022-04-13,2022-04-13
2319610,9EC4C49BE4CB1A09,classic_bike,2022-04-12 15:58:47,2022-04-12 16:41:17,E 88 St & 1 Ave,7235.13,E 91 St & 2 Ave,7286.01,40.778301,-73.948813,...,Tuesday,Tuesday,15,16,April,April,2022,2022,2022-04-12,2022-04-12
2319611,C0188AB9FAEAA143,electric_bike,2022-04-28 15:52:49,2022-04-28 16:06:31,W 55 St & 6 Ave,6809.09,E 91 St & 2 Ave,7286.01,40.763189,-73.978434,...,Thursday,Thursday,15,16,April,April,2022,2022,2022-04-28,2022-04-28
2319612,E8C2F305866DF134,electric_bike,2022-04-11 19:55:31,2022-04-11 20:09:19,W 87 St & West End Ave,7484.05,E 91 St & 2 Ave,7286.01,40.789622,-73.977570,...,Monday,Monday,19,20,April,April,2022,2022,2022-04-11,2022-04-11

# 5) Outliers

In [29]:
# Statistical description of dataframe
# Unusually the bike ride lasts over 50000 minutes
# There is a monetary penalty for rides longer than 45 minutes for members and 30 minutes for casual customers, it is improbable than any rides will much longer. The System host site indicates that for distance calculation, trips are capped at a 2 hour limit and we will use a similar approach.
# It is highly probable that the bike was not engaged properly at the returning station.

bikes.describe()

,start_lat,start_lng,end_lat,end_lng,time_spent_with_bike,time_spent_with_bike_in_minutes,started_at_hour,ended_at_hour,started_at_year,ended_at_year
count,6.483439e+06,6.483439e+06,6.483439e+06,6.483439e+06,6.483439e+06,6.483439e+06,6.483439e+06,6.483439e+06,6483439.0,6483439.0
mean,4.074005e+01,-7.397657e+01,4.073983e+01,-7.397673e+01,8.464783e+02,1.410797e+01,1.394592e+01,1.408894e+01,2022.0,2022.0
std,3.732827e-02,2.397125e-02,3.718403e-02,2.398756e-02,3.767576e+03,6.279293e+01,4.817198e+00,4.863344e+00,0.0,0.0
min,4.063338e+01,-7.402747e+01,4.063338e+01,-7.407146e+01,-5.240000e+02,-8.730000e+00,0.000000e+00,0.000000e+00,2022.0,2022.0
25%,4.071689e+01,-7.399344e+01,4.071689e+01,-7.399379e+01,3.150000e+02,5.250000e+00,1.000000e+01,1.100000e+01,2022.0,2022.0
50%,4.073945e+01,-7.398178e+01,4.073936e+01,-7.398192e+01,5.560000e+02,9.270000e+00,1.500000e+01,1.500000e+01,2022.0,2022.0
75%,4.076270e+01,-7.396222e+01,4.076227e+01,-7.396222e+01,9.780000e+02,1.630000e+01,1.800000e+01,1.800000e+01,2022.0,2022.0
max,4.088226e+01,-7.388145e+01,4.088226e+01,-7.388145e+01,3.479159e+06,5.798598e+04,2.300000e+01,2.300000e+01,2022.0,2022.0

In [30]:
# We will filter out any trips greater than 2 hours.
bikes = bikes[bikes['time_spent_with_bike_in_minutes']<=120]
bikes

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,started_at_day_name,ended_at_day_name,started_at_hour,ended_at_hour,started_at_month_name,ended_at_month_name,started_at_year,ended_at_year,started_at_date,ended_at_date
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,...,Tuesday,Tuesday,8,8,January,January,2022,2022,2022-01-18,2022-01-18
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,...,Friday,Friday,9,9,January,January,2022,2022,2022-01-21,2022-01-21
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,...,Saturday,Saturday,14,14,January,January,2022,2022,2022-01-22,2022-01-22
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,...,Wednesday,Wednesday,14,14,January,January,2022,2022,2022-01-19,2022-01-19
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,...,Sunday,Sunday,14,14,January,January,2022,2022,2022-01-16,2022-01-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2319608,5EBE9D296B9D3E3C,classic_bike,2022-04-22 13:08:15,2022-04-22 13:29:31,Allen St & Rivington St,5414.06,W 29 St & 9 Ave,6416.06,40.720196,-73.989978,...,Friday,Friday,13,13,April,April,2022,2022,2022-04-22,2022-04-22
2319609,B66382DEDA84C464,classic_bike,2022-04-13 17:10:49,2022-04-13 17:26:08,St. Nicholas Terrace & Convent Ave,7937.15,E 138 St & Grand Concourse,7803.08,40.821294,-73.947868,...,Wednesday,Wednesday,17,17,April,April,2022,2022,2022-04-13,2022-04-13
2319610,9EC4C49BE4CB1A09,classic_bike,2022-04-12 15:58:47,2022-04-12 16:41:17,E 88 St & 1 Ave,7235.13,E 91 St & 2 Ave,7286.01,40.778301,-73.948813,...,Tuesday,Tuesday,15,16,April,April,2022,2022,2022-04-12,2022-04-12
2319611,C0188AB9FAEAA143,electric_bike,2022-04-28 15:52:49,2022-04-28 16:06:31,W 55 St & 6 Ave,6809.09,E 91 St & 2 Ave,7286.01,40.763189,-73.978434,...,Thursday,Thursday,15,16,April,April,2022,2022,2022-04-28,2022-04-28
2319612,E8C2F305866DF134,electric_bike,2022-04-11 19:55:31,2022-04-11 20:09:19,W 87 St & West End Ave,7484.05,E 91 St & 2 Ave,7286.01,40.789622,-73.977570,...,Monday,Monday,19,20,April,April,2022,2022,2022-04-11,2022-04-11

# 6) Rearranging Columns and Exporting Finalized Dataframe to Desktop

In [31]:
# Returning the name of all columns of dataframe

bikes.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual', 'time_spent_with_bike',
       'time_spent_with_bike_in_minutes', 'started_at_day_name',
       'ended_at_day_name', 'started_at_hour', 'ended_at_hour',
       'started_at_month_name', 'ended_at_month_name', 'started_at_year',
       'ended_at_year', 'started_at_date', 'ended_at_date'],
      dtype='object')

In [32]:
# Selected and rearranged several columns for dataframe

bikes = bikes[['ride_id', 'rideable_type', 'started_at', 'ended_at', 'started_at_date', 'ended_at_date', 'started_at_year', 'ended_at_year',
               'started_at_month_name', 'ended_at_month_name', 'started_at_day_name', 'ended_at_day_name','started_at_hour', 'ended_at_hour', 
               'started_at_date', 'start_station_name', 'end_station_name',
                'start_lat', 'start_lng', 'end_lat', 'end_lng', 'member_casual', 'time_spent_with_bike_in_minutes']]
bikes

,ride_id,rideable_type,started_at,ended_at,started_at_date,ended_at_date,started_at_year,ended_at_year,started_at_month_name,ended_at_month_name,...,ended_at_hour,started_at_date,start_station_name,end_station_name,start_lat,start_lng,end_lat,end_lng,member_casual,time_spent_with_bike_in_minutes
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,2022-01-18,2022-01-18,2022,2022,January,January,...,8,2022-01-18,Boerum Pl\t& Pacific St,Clinton St & Joralemon St,40.688489,-73.991160,40.692395,-73.993379,member,4.43
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,2022-01-21,2022-01-21,2022,2022,January,January,...,9,2022-01-21,E 12 St & Ave C,E 10 St & Avenue A,40.727243,-73.976831,40.727408,-73.981420,member,2.37
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,2022-01-22,2022-01-22,2022,2022,January,January,...,14,2022-01-22,W 21 St & 6 Ave,W 44 St & 11 Ave,40.741740,-73.994156,40.762009,-73.996975,member,24.77
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,2022-01-19,2022-01-19,2022,2022,January,January,...,14,2022-01-19,38 St & 30 Ave,Crescent St & 30 Ave,40.764175,-73.915840,40.768692,-73.924957,member,4.25
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,2022-01-16,2022-01-16,2022,2022,January,January,...,14,2022-01-16,Pacific St & Nevins St,Clinton St & Tillary St,40.685376,-73.983021,40.696233,-73.991421,member,8.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2319608,5EBE9D296B9D3E3C,classic_bike,2022-04-22 13:08:15,2022-04-22 13:29:31,2022-04-22,2022-04-22,2022,2022,April,April,...,13,2022-04-22,Allen St & Rivington St,W 29 St & 9 Ave,40.720196,-73.989978,40.750073,-73.998393,member,21.27
2319609,B66382DEDA84C464,classic_bike,2022-04-13 17:10:49,2022-04-13 17:26:08,2022-04-13,2022-04-13,2022,2022,April,April,...,17,2022-04-13,St. Nicholas Terrace & Convent Ave,E 138 St & Grand Concourse,40.821294,-73.947868,40.813224,-73.930605,member,15.32
2319610,9EC4C49BE4CB1A09,classic_bike,2022-04-12 15:58:47,2022-04-12 16:41:17,2022-04-12,2022-04-12,2022,2022,April,April,...,16,2022-04-12,E 88 St & 1 Ave,E 91 St & 2 Ave,40.778301,-73.948813,40.781153,-73.949630,member,42.50
2319611,C0188AB9FAEAA143,electric_bike,2022-04-28 15:52:49,2022-04-28 16:06:31,2022-04-28,2022-04-28,2022,2022,April,April,...,16,2022-04-28,W 55 St & 6 Ave,E 91 St & 2 Ave,40.763189,-73.978434,40.781153,-73.949630,member,13.70
2319612,E8C2F305866DF134,electric_bike,2022-04-11 19:55:31,2022-04-11 20:09:19,2022-04-11,2022-04-11,2022,2022,April,April,...,20,2022-04-11,W 87 St & West End Ave,E 91 St & 2 Ave,40.789622,-73.977570,40.781153,-73.949630,member,13.80

In [33]:
# Exporting finalized dataframe

bikes.to_csv(os.path.join(path, 'Desktop', 'bikes_nyc_2022.csv'))