# 4) Importing Libraries and DataFrame

In [1]:
# Importing libraries

import pandas as pd
import numpy as np
import os
from datetime import datetime

In [2]:
# Importing nyc_bikes_2023 combined dataframe

path = r'/Users/matthewabrams/'

nyc_bikes_2023 = pd.read_csv(os.path.join(path, 'Desktop', 'bikes_2023-2024_combined.csv'), index_col = False)
nyc_bikes_2023.drop(columns = ['Unnamed: 0'], inplace = True)
nyc_bikes_2023

/Users/matthewabrams/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (6,8) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,4A86C1475DCCADA0,classic_bike,2023-01-26 10:53:44,2023-01-26 11:05:17,E 53 St & Madison Ave,6659.03,Columbus Ave & W 72 St,7175.05,40.759724,-73.973664,40.777057,-73.978985,member
1,AE02E1FF7E264874,classic_bike,2023-01-04 11:51:54,2023-01-04 12:07:09,Halsey St & Ralph Ave,4334.02,Clinton Ave & Myrtle Ave,4651.02,40.684970,-73.922755,40.693261,-73.968896,casual
2,D3F9A2A71AD244C6,classic_bike,2023-01-04 17:26:48,2023-01-04 17:43:29,Bank St & Hudson St,5922.08,W 52 St & 11 Ave,6926.01,40.736566,-74.006092,40.767272,-73.993929,casual
3,3D48C6F33AFEF329,classic_bike,2023-01-04 08:31:11,2023-01-04 08:42:12,E 53 St & Madison Ave,6659.03,W 45 St & 8 Ave,6676.02,40.759711,-73.974023,40.759291,-73.988597,member
4,4865926C3D97BA01,electric_bike,2023-01-03 22:15:34,2023-01-03 22:30:35,Frederick Douglass Blvd & W 112 St,7631.23,Central Park S & 6 Ave,6876.04,40.801694,-73.957145,40.765909,-73.976342,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
36157804,ADDC132B2781F4ED,electric_bike,2023-12-17 12:29:57.955,2023-12-17 12:33:43.211,W 76 St & Columbus Ave,7281.09,Amsterdam Ave & W 82 St,7360.1,40.780184,-73.977285,40.785247,-73.976673,member
36157805,C2A1CE9F5D86CEBC,electric_bike,2023-12-15 12:25:50.809,2023-12-15 12:39:32.176,Fresh Pond Rd & 69 Ave,4945.06,Myrtle Ave & Marcy Ave,4707.03,40.703139,-73.895477,40.695398,-73.949549,member
36157806,38A28CE39397CA1E,classic_bike,2023-12-12 17:11:16.792,2023-12-12 17:17:45.781,Ocean Ave & Crooke Ave,3408.05,Lincoln Rd & Ocean Ave,3633.08,40.653260,-73.961720,40.660500,-73.962600,member
36157807,B9C000D3EECE6A8F,electric_bike,2023-12-26 19:10:18.563,2023-12-26 19:14:48.843,Maiden Ln & Pearl St,5065.10,Centre St & Chambers St,5207.01,40.752142,-73.993647,40.712733,-74.004607,member
36157808,D12C9B14AD682510,classic_bike,2023-12-09 16:20:57.967,2023-12-09 16:25:35.530,Lincoln Ave & E 138 St,7744.06,Willis Ave & Bruckner Blvd,7691.05,40.810893,-73.927311,40.805701,-73.925177,member

In [3]:
# Importing nyc_bikes_2022 combined dataframe

nyc_bikes_2022 = pd.read_csv(os.path.join(path, 'Desktop', 'bikes_2022-2023_combined.csv'), index_col = False)
nyc_bikes_2022.drop(columns = ['Unnamed: 0'], inplace = True)
nyc_bikes_2022

/Users/matthewabrams/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (6,8) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,40.692395,-73.993379,member
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,40.727408,-73.981420,member
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,40.762009,-73.996975,member
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,40.768692,-73.924957,member
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,40.696233,-73.991421,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
30632313,1F223EDAFF420AE3,electric_bike,2022-12-01 20:26:45.847,2022-12-01 20:30:46.012,Avenue D & E 3 St,5436.09,Stanton St & Chrystie St,5523.02,40.720701,-73.977939,40.722293,-73.991475,member
30632314,CFA5C560ACB73B8E,classic_bike,2022-12-26 13:46:34.237,2022-12-26 13:52:43.900,43 Ave & 47 St,6209.05,39 Ave & 45 St,6401.03,40.744806,-73.917290,40.749478,-73.918265,member
30632315,11C8C5E0DB947B07,classic_bike,2022-12-01 05:56:14.903,2022-12-01 06:06:10.357,Avenue D & E 3 St,5436.09,Bleecker St & Crosby St,5679.08,40.720828,-73.977932,40.726156,-73.995102,member
30632316,5B9B083C534A5964,classic_bike,2022-12-02 11:54:15.871,2022-12-02 12:01:00.747,Montague St & Clinton St,4677.06,Sands St & Jay St,4821.03,40.694271,-73.992327,40.700119,-73.986200,member
30632317,91C286C462F89A50,classic_bike,2022-12-18 13:35:22.574,2022-12-18 13:37:27.193,Montague St & Clinton St,4677.06,Cadman Plaza E & Tillary St,4677.01,40.694271,-73.992327,40.695977,-73.990149,member

# 5) Checking for missing values, duplicates, and inconsistant values

In [4]:
# Checking for null values of nyc_bikes_2023

nyc_bikes_2023.isnull().sum()

ride_id                    0
rideable_type              0
started_at                 0
ended_at                   0
start_station_name     18644
start_station_id       18644
end_station_name      103266
end_station_id        103266
start_lat                  0
start_lng                  0
end_lat                26207
end_lng                26207
member_casual              0
dtype: int64

In [5]:
# Checking for null values of nyc_bikes_2022

nyc_bikes_2022.isnull().sum()

ride_id                   0
rideable_type             0
started_at                0
ended_at                  0
start_station_name       49
start_station_id         49
end_station_name      71321
end_station_id        71321
start_lat                 0
start_lng                 0
end_lat               37481
end_lng               37481
member_casual             0
dtype: int64

In [6]:
# For nyc_bikes_2023 Dropping null values under'start_station_name','end_station_name'
# Want to return all known values for where people bike from and where to

nyc_bikes_2023.dropna(subset = ['start_station_name','end_station_name'], inplace = True)
nyc_bikes_2023

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,4A86C1475DCCADA0,classic_bike,2023-01-26 10:53:44,2023-01-26 11:05:17,E 53 St & Madison Ave,6659.03,Columbus Ave & W 72 St,7175.05,40.759724,-73.973664,40.777057,-73.978985,member
1,AE02E1FF7E264874,classic_bike,2023-01-04 11:51:54,2023-01-04 12:07:09,Halsey St & Ralph Ave,4334.02,Clinton Ave & Myrtle Ave,4651.02,40.684970,-73.922755,40.693261,-73.968896,casual
2,D3F9A2A71AD244C6,classic_bike,2023-01-04 17:26:48,2023-01-04 17:43:29,Bank St & Hudson St,5922.08,W 52 St & 11 Ave,6926.01,40.736566,-74.006092,40.767272,-73.993929,casual
3,3D48C6F33AFEF329,classic_bike,2023-01-04 08:31:11,2023-01-04 08:42:12,E 53 St & Madison Ave,6659.03,W 45 St & 8 Ave,6676.02,40.759711,-73.974023,40.759291,-73.988597,member
4,4865926C3D97BA01,electric_bike,2023-01-03 22:15:34,2023-01-03 22:30:35,Frederick Douglass Blvd & W 112 St,7631.23,Central Park S & 6 Ave,6876.04,40.801694,-73.957145,40.765909,-73.976342,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
36157804,ADDC132B2781F4ED,electric_bike,2023-12-17 12:29:57.955,2023-12-17 12:33:43.211,W 76 St & Columbus Ave,7281.09,Amsterdam Ave & W 82 St,7360.1,40.780184,-73.977285,40.785247,-73.976673,member
36157805,C2A1CE9F5D86CEBC,electric_bike,2023-12-15 12:25:50.809,2023-12-15 12:39:32.176,Fresh Pond Rd & 69 Ave,4945.06,Myrtle Ave & Marcy Ave,4707.03,40.703139,-73.895477,40.695398,-73.949549,member
36157806,38A28CE39397CA1E,classic_bike,2023-12-12 17:11:16.792,2023-12-12 17:17:45.781,Ocean Ave & Crooke Ave,3408.05,Lincoln Rd & Ocean Ave,3633.08,40.653260,-73.961720,40.660500,-73.962600,member
36157807,B9C000D3EECE6A8F,electric_bike,2023-12-26 19:10:18.563,2023-12-26 19:14:48.843,Maiden Ln & Pearl St,5065.10,Centre St & Chambers St,5207.01,40.752142,-73.993647,40.712733,-74.004607,member
36157808,D12C9B14AD682510,classic_bike,2023-12-09 16:20:57.967,2023-12-09 16:25:35.530,Lincoln Ave & E 138 St,7744.06,Willis Ave & Bruckner Blvd,7691.05,40.810893,-73.927311,40.805701,-73.925177,member

In [7]:
# For nyc_bikes_2022 Dropping null values under'start_station_name','end_station_name'
# Want to return all known values for where people bike from and where to

nyc_bikes_2022.dropna(subset = ['start_station_name','end_station_name'], inplace = True)
nyc_bikes_2022

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,40.692395,-73.993379,member
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,40.727408,-73.981420,member
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,40.762009,-73.996975,member
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,40.768692,-73.924957,member
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,40.696233,-73.991421,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
30632313,1F223EDAFF420AE3,electric_bike,2022-12-01 20:26:45.847,2022-12-01 20:30:46.012,Avenue D & E 3 St,5436.09,Stanton St & Chrystie St,5523.02,40.720701,-73.977939,40.722293,-73.991475,member
30632314,CFA5C560ACB73B8E,classic_bike,2022-12-26 13:46:34.237,2022-12-26 13:52:43.900,43 Ave & 47 St,6209.05,39 Ave & 45 St,6401.03,40.744806,-73.917290,40.749478,-73.918265,member
30632315,11C8C5E0DB947B07,classic_bike,2022-12-01 05:56:14.903,2022-12-01 06:06:10.357,Avenue D & E 3 St,5436.09,Bleecker St & Crosby St,5679.08,40.720828,-73.977932,40.726156,-73.995102,member
30632316,5B9B083C534A5964,classic_bike,2022-12-02 11:54:15.871,2022-12-02 12:01:00.747,Montague St & Clinton St,4677.06,Sands St & Jay St,4821.03,40.694271,-73.992327,40.700119,-73.986200,member
30632317,91C286C462F89A50,classic_bike,2022-12-18 13:35:22.574,2022-12-18 13:37:27.193,Montague St & Clinton St,4677.06,Cadman Plaza E & Tillary St,4677.01,40.694271,-73.992327,40.695977,-73.990149,member

In [8]:
# For nyc_bikes_2023 Checking for duplicates
# No duplicates

nyc_bikes_2023[nyc_bikes_2023.duplicated()]

Empty DataFrame
Columns: [ride_id, rideable_type, started_at, ended_at, start_station_name, start_station_id, end_station_name, end_station_id, start_lat, start_lng, end_lat, end_lng, member_casual]
Index: []

In [9]:
# For nyc_bikes_2022 Checking for duplicates
# No duplicates

nyc_bikes_2022[nyc_bikes_2022.duplicated()]

Empty DataFrame
Columns: [ride_id, rideable_type, started_at, ended_at, start_station_name, start_station_id, end_station_name, end_station_id, start_lat, start_lng, end_lat, end_lng, member_casual]
Index: []

In [10]:
nyc_bikes_2023['start_station_name'].value_counts()

W 21 St & 6 Ave            142235
Broadway & W 58 St         118518
West St & Chambers St      113703
University Pl & E 14 St    111185
11 Ave & W 41 St           110601
                            ...
Leonard Gordon Park             1
Dey St                          1
Bergen Ave & Stegman St         1
Brunswick & 6th                 1
Grand St & 14 St                1
Name: start_station_name, Length: 2305, dtype: int64

In [11]:
nyc_bikes_2022['start_station_name'].value_counts()

W 21 St & 6 Ave                   131263
West St & Chambers St             125944
Broadway & W 58 St                117274
6 Ave & W 33 St                   109129
1 Ave & E 68 St                   108025
                                   ...
W 40 St & 8 Ave                        8
Lexington Ave & Stuyvesant Ave         8
E 6 St 2 Ave                           7
Sharon St & Olive St_new               4
Schermerhorn St and Court St           2
Name: start_station_name, Length: 1761, dtype: int64

In [12]:
nyc_bikes_2023['end_station_name'].value_counts()

W 21 St & 6 Ave               142844
Broadway & W 58 St            115466
West St & Chambers St         114476
University Pl & E 14 St       111772
11 Ave & W 41 St              110776
                               ...
Shop Morgan                        1
Union St                           1
Columbus Dr at Exchange Pl         1
Jackson Square                     1
Lincoln Park                       1
Name: end_station_name, Length: 2315, dtype: int64

In [13]:
nyc_bikes_2022['end_station_name'].value_counts()

W 21 St & 6 Ave                       132608
West St & Chambers St                 127233
Broadway & W 58 St                    113273
1 Ave & E 68 St                       108461
6 Ave & W 33 St                       107476
                                       ...
Clinton St & 7 St                          1
NYCBS DEPOT - DELANCEY                     1
Hoboken Ave at Monmouth St                 1
Apache                                     1
Sedgwick Ave & W Tremont Ave - new         1
Name: end_station_name, Length: 1841, dtype: int64

In [14]:
# Finding how many types of ridable bikes there are in 2023
# There are three types of rideable bikes

nyc_bikes_2023['rideable_type'].unique()

array(['classic_bike', 'electric_bike', 'docked_bike'], dtype=object)

In [15]:
# Finding how many types of ridable bikes there are in 2022
# There are three types of rideable bikes

nyc_bikes_2022['rideable_type'].unique()

array(['classic_bike', 'electric_bike', 'docked_bike'], dtype=object)

In [16]:
nyc_bikes_2023['member_casual'].unique()

array(['member', 'casual'], dtype=object)

In [17]:
nyc_bikes_2022['member_casual'].unique()

array(['member', 'casual'], dtype=object)

# 6) Changing datatypes and adding new columns

In [18]:
# Changing datatype of column from object to datestamp

nyc_bikes_2023['started_at'] = pd.to_datetime(nyc_bikes_2023['started_at'])

In [19]:
nyc_bikes_2022['started_at'] = pd.to_datetime(nyc_bikes_2022['started_at'])

In [20]:
# Changing datatype of column from object to datestamp

nyc_bikes_2023['ended_at'] = pd.to_datetime(nyc_bikes_2023['ended_at'])

In [21]:
nyc_bikes_2022['ended_at'] = pd.to_datetime(nyc_bikes_2022['ended_at'])

In [22]:
# Checking for changes made in datatypes of each column

nyc_bikes_2023.dtypes

ride_id                       object
rideable_type                 object
started_at            datetime64[ns]
ended_at              datetime64[ns]
start_station_name            object
start_station_id              object
end_station_name              object
end_station_id                object
start_lat                    float64
start_lng                    float64
end_lat                      float64
end_lng                      float64
member_casual                 object
dtype: object

In [23]:
nyc_bikes_2022.dtypes

ride_id                       object
rideable_type                 object
started_at            datetime64[ns]
ended_at              datetime64[ns]
start_station_name            object
start_station_id              object
end_station_name              object
end_station_id                object
start_lat                    float64
start_lng                    float64
end_lat                      float64
end_lng                      float64
member_casual                 object
dtype: object

In [24]:
# Creating column for how much time spent on bike ride, labeled "time_spent_with_bike"
# Formula was derived from taking the difference between "ended_at" and "started_at" column

nyc_bikes_2023["time_spent_with_bike"] = abs(nyc_bikes_2023['ended_at'] - nyc_bikes_2023['started_at'])
nyc_bikes_2023

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,time_spent_with_bike
0,4A86C1475DCCADA0,classic_bike,2023-01-26 10:53:44.000,2023-01-26 11:05:17.000,E 53 St & Madison Ave,6659.03,Columbus Ave & W 72 St,7175.05,40.759724,-73.973664,40.777057,-73.978985,member,0 days 00:11:33
1,AE02E1FF7E264874,classic_bike,2023-01-04 11:51:54.000,2023-01-04 12:07:09.000,Halsey St & Ralph Ave,4334.02,Clinton Ave & Myrtle Ave,4651.02,40.684970,-73.922755,40.693261,-73.968896,casual,0 days 00:15:15
2,D3F9A2A71AD244C6,classic_bike,2023-01-04 17:26:48.000,2023-01-04 17:43:29.000,Bank St & Hudson St,5922.08,W 52 St & 11 Ave,6926.01,40.736566,-74.006092,40.767272,-73.993929,casual,0 days 00:16:41
3,3D48C6F33AFEF329,classic_bike,2023-01-04 08:31:11.000,2023-01-04 08:42:12.000,E 53 St & Madison Ave,6659.03,W 45 St & 8 Ave,6676.02,40.759711,-73.974023,40.759291,-73.988597,member,0 days 00:11:01
4,4865926C3D97BA01,electric_bike,2023-01-03 22:15:34.000,2023-01-03 22:30:35.000,Frederick Douglass Blvd & W 112 St,7631.23,Central Park S & 6 Ave,6876.04,40.801694,-73.957145,40.765909,-73.976342,casual,0 days 00:15:01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36157804,ADDC132B2781F4ED,electric_bike,2023-12-17 12:29:57.955,2023-12-17 12:33:43.211,W 76 St & Columbus Ave,7281.09,Amsterdam Ave & W 82 St,7360.1,40.780184,-73.977285,40.785247,-73.976673,member,0 days 00:03:45.256000
36157805,C2A1CE9F5D86CEBC,electric_bike,2023-12-15 12:25:50.809,2023-12-15 12:39:32.176,Fresh Pond Rd & 69 Ave,4945.06,Myrtle Ave & Marcy Ave,4707.03,40.703139,-73.895477,40.695398,-73.949549,member,0 days 00:13:41.367000
36157806,38A28CE39397CA1E,classic_bike,2023-12-12 17:11:16.792,2023-12-12 17:17:45.781,Ocean Ave & Crooke Ave,3408.05,Lincoln Rd & Ocean Ave,3633.08,40.653260,-73.961720,40.660500,-73.962600,member,0 days 00:06:28.989000
36157807,B9C000D3EECE6A8F,electric_bike,2023-12-26 19:10:18.563,2023-12-26 19:14:48.843,Maiden Ln & Pearl St,5065.10,Centre St & Chambers St,5207.01,40.752142,-73.993647,40.712733,-74.004607,member,0 days 00:04:30.280000
36157808,D12C9B14AD682510,classic_bike,2023-12-09 16:20:57.967,2023-12-09 16:25:35.530,Lincoln Ave & E 138 St,7744.06,Willis Ave & Bruckner Blvd,7691.05,40.810893,-73.927311,40.805701,-73.925177,member,0 days 00:04:37.563000

In [25]:
nyc_bikes_2022["time_spent_with_bike"] = abs(nyc_bikes_2022['ended_at'] - nyc_bikes_2022['started_at'])
nyc_bikes_2022

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,time_spent_with_bike
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52.000,2022-01-18 08:28:18.000,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,40.692395,-73.993379,member,0 days 00:04:26
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22.000,2022-01-21 09:05:44.000,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,40.727408,-73.981420,member,0 days 00:02:22
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32.000,2022-01-22 14:53:18.000,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,40.762009,-73.996975,member,0 days 00:24:46
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47.000,2022-01-19 14:54:02.000,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,40.768692,-73.924957,member,0 days 00:04:15
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06.000,2022-01-16 14:44:06.000,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,40.696233,-73.991421,member,0 days 00:08:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30632313,1F223EDAFF420AE3,electric_bike,2022-12-01 20:26:45.847,2022-12-01 20:30:46.012,Avenue D & E 3 St,5436.09,Stanton St & Chrystie St,5523.02,40.720701,-73.977939,40.722293,-73.991475,member,0 days 00:04:00.165000
30632314,CFA5C560ACB73B8E,classic_bike,2022-12-26 13:46:34.237,2022-12-26 13:52:43.900,43 Ave & 47 St,6209.05,39 Ave & 45 St,6401.03,40.744806,-73.917290,40.749478,-73.918265,member,0 days 00:06:09.663000
30632315,11C8C5E0DB947B07,classic_bike,2022-12-01 05:56:14.903,2022-12-01 06:06:10.357,Avenue D & E 3 St,5436.09,Bleecker St & Crosby St,5679.08,40.720828,-73.977932,40.726156,-73.995102,member,0 days 00:09:55.454000
30632316,5B9B083C534A5964,classic_bike,2022-12-02 11:54:15.871,2022-12-02 12:01:00.747,Montague St & Clinton St,4677.06,Sands St & Jay St,4821.03,40.694271,-73.992327,40.700119,-73.986200,member,0 days 00:06:44.876000
30632317,91C286C462F89A50,classic_bike,2022-12-18 13:35:22.574,2022-12-18 13:37:27.193,Montague St & Clinton St,4677.06,Cadman Plaza E & Tillary St,4677.01,40.694271,-73.992327,40.695977,-73.990149,member,0 days 00:02:04.619000

In [26]:
# Changed data type of 'time_spent_with_bike' column to an integer and also converted time spent to total seconds

nyc_bikes_2023['time_spent_with_bike'] = nyc_bikes_2023['time_spent_with_bike'].dt.total_seconds().astype(int)
nyc_bikes_2023

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,time_spent_with_bike
0,4A86C1475DCCADA0,classic_bike,2023-01-26 10:53:44.000,2023-01-26 11:05:17.000,E 53 St & Madison Ave,6659.03,Columbus Ave & W 72 St,7175.05,40.759724,-73.973664,40.777057,-73.978985,member,693
1,AE02E1FF7E264874,classic_bike,2023-01-04 11:51:54.000,2023-01-04 12:07:09.000,Halsey St & Ralph Ave,4334.02,Clinton Ave & Myrtle Ave,4651.02,40.684970,-73.922755,40.693261,-73.968896,casual,915
2,D3F9A2A71AD244C6,classic_bike,2023-01-04 17:26:48.000,2023-01-04 17:43:29.000,Bank St & Hudson St,5922.08,W 52 St & 11 Ave,6926.01,40.736566,-74.006092,40.767272,-73.993929,casual,1001
3,3D48C6F33AFEF329,classic_bike,2023-01-04 08:31:11.000,2023-01-04 08:42:12.000,E 53 St & Madison Ave,6659.03,W 45 St & 8 Ave,6676.02,40.759711,-73.974023,40.759291,-73.988597,member,661
4,4865926C3D97BA01,electric_bike,2023-01-03 22:15:34.000,2023-01-03 22:30:35.000,Frederick Douglass Blvd & W 112 St,7631.23,Central Park S & 6 Ave,6876.04,40.801694,-73.957145,40.765909,-73.976342,casual,901
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36157804,ADDC132B2781F4ED,electric_bike,2023-12-17 12:29:57.955,2023-12-17 12:33:43.211,W 76 St & Columbus Ave,7281.09,Amsterdam Ave & W 82 St,7360.1,40.780184,-73.977285,40.785247,-73.976673,member,225
36157805,C2A1CE9F5D86CEBC,electric_bike,2023-12-15 12:25:50.809,2023-12-15 12:39:32.176,Fresh Pond Rd & 69 Ave,4945.06,Myrtle Ave & Marcy Ave,4707.03,40.703139,-73.895477,40.695398,-73.949549,member,821
36157806,38A28CE39397CA1E,classic_bike,2023-12-12 17:11:16.792,2023-12-12 17:17:45.781,Ocean Ave & Crooke Ave,3408.05,Lincoln Rd & Ocean Ave,3633.08,40.653260,-73.961720,40.660500,-73.962600,member,388
36157807,B9C000D3EECE6A8F,electric_bike,2023-12-26 19:10:18.563,2023-12-26 19:14:48.843,Maiden Ln & Pearl St,5065.10,Centre St & Chambers St,5207.01,40.752142,-73.993647,40.712733,-74.004607,member,270
36157808,D12C9B14AD682510,classic_bike,2023-12-09 16:20:57.967,2023-12-09 16:25:35.530,Lincoln Ave & E 138 St,7744.06,Willis Ave & Bruckner Blvd,7691.05,40.810893,-73.927311,40.805701,-73.925177,member,277

In [27]:
nyc_bikes_2022['time_spent_with_bike'] = nyc_bikes_2022['time_spent_with_bike'].dt.total_seconds().astype(int)
nyc_bikes_2022

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,time_spent_with_bike
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52.000,2022-01-18 08:28:18.000,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,40.692395,-73.993379,member,266
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22.000,2022-01-21 09:05:44.000,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,40.727408,-73.981420,member,142
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32.000,2022-01-22 14:53:18.000,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,40.762009,-73.996975,member,1486
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47.000,2022-01-19 14:54:02.000,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,40.768692,-73.924957,member,255
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06.000,2022-01-16 14:44:06.000,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,40.696233,-73.991421,member,480
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30632313,1F223EDAFF420AE3,electric_bike,2022-12-01 20:26:45.847,2022-12-01 20:30:46.012,Avenue D & E 3 St,5436.09,Stanton St & Chrystie St,5523.02,40.720701,-73.977939,40.722293,-73.991475,member,240
30632314,CFA5C560ACB73B8E,classic_bike,2022-12-26 13:46:34.237,2022-12-26 13:52:43.900,43 Ave & 47 St,6209.05,39 Ave & 45 St,6401.03,40.744806,-73.917290,40.749478,-73.918265,member,369
30632315,11C8C5E0DB947B07,classic_bike,2022-12-01 05:56:14.903,2022-12-01 06:06:10.357,Avenue D & E 3 St,5436.09,Bleecker St & Crosby St,5679.08,40.720828,-73.977932,40.726156,-73.995102,member,595
30632316,5B9B083C534A5964,classic_bike,2022-12-02 11:54:15.871,2022-12-02 12:01:00.747,Montague St & Clinton St,4677.06,Sands St & Jay St,4821.03,40.694271,-73.992327,40.700119,-73.986200,member,404
30632317,91C286C462F89A50,classic_bike,2022-12-18 13:35:22.574,2022-12-18 13:37:27.193,Montague St & Clinton St,4677.06,Cadman Plaza E & Tillary St,4677.01,40.694271,-73.992327,40.695977,-73.990149,member,124

In [28]:
# Created new column derived from 'time_spent_with_bike'
# Converted time spent from total seconds to minutes (nearest two places after decimal)

nyc_bikes_2023['time_spent_with_bike_in_minutes'] = round((nyc_bikes_2023['time_spent_with_bike']/60),2)
nyc_bikes_2023

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,time_spent_with_bike,time_spent_with_bike_in_minutes
0,4A86C1475DCCADA0,classic_bike,2023-01-26 10:53:44.000,2023-01-26 11:05:17.000,E 53 St & Madison Ave,6659.03,Columbus Ave & W 72 St,7175.05,40.759724,-73.973664,40.777057,-73.978985,member,693,11.55
1,AE02E1FF7E264874,classic_bike,2023-01-04 11:51:54.000,2023-01-04 12:07:09.000,Halsey St & Ralph Ave,4334.02,Clinton Ave & Myrtle Ave,4651.02,40.684970,-73.922755,40.693261,-73.968896,casual,915,15.25
2,D3F9A2A71AD244C6,classic_bike,2023-01-04 17:26:48.000,2023-01-04 17:43:29.000,Bank St & Hudson St,5922.08,W 52 St & 11 Ave,6926.01,40.736566,-74.006092,40.767272,-73.993929,casual,1001,16.68
3,3D48C6F33AFEF329,classic_bike,2023-01-04 08:31:11.000,2023-01-04 08:42:12.000,E 53 St & Madison Ave,6659.03,W 45 St & 8 Ave,6676.02,40.759711,-73.974023,40.759291,-73.988597,member,661,11.02
4,4865926C3D97BA01,electric_bike,2023-01-03 22:15:34.000,2023-01-03 22:30:35.000,Frederick Douglass Blvd & W 112 St,7631.23,Central Park S & 6 Ave,6876.04,40.801694,-73.957145,40.765909,-73.976342,casual,901,15.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36157804,ADDC132B2781F4ED,electric_bike,2023-12-17 12:29:57.955,2023-12-17 12:33:43.211,W 76 St & Columbus Ave,7281.09,Amsterdam Ave & W 82 St,7360.1,40.780184,-73.977285,40.785247,-73.976673,member,225,3.75
36157805,C2A1CE9F5D86CEBC,electric_bike,2023-12-15 12:25:50.809,2023-12-15 12:39:32.176,Fresh Pond Rd & 69 Ave,4945.06,Myrtle Ave & Marcy Ave,4707.03,40.703139,-73.895477,40.695398,-73.949549,member,821,13.68
36157806,38A28CE39397CA1E,classic_bike,2023-12-12 17:11:16.792,2023-12-12 17:17:45.781,Ocean Ave & Crooke Ave,3408.05,Lincoln Rd & Ocean Ave,3633.08,40.653260,-73.961720,40.660500,-73.962600,member,388,6.47
36157807,B9C000D3EECE6A8F,electric_bike,2023-12-26 19:10:18.563,2023-12-26 19:14:48.843,Maiden Ln & Pearl St,5065.10,Centre St & Chambers St,5207.01,40.752142,-73.993647,40.712733,-74.004607,member,270,4.50
36157808,D12C9B14AD682510,classic_bike,2023-12-09 16:20:57.967,2023-12-09 16:25:35.530,Lincoln Ave & E 138 St,7744.06,Willis Ave & Bruckner Blvd,7691.05,40.810893,-73.927311,40.805701,-73.925177,member,277,4.62

In [29]:
nyc_bikes_2022['time_spent_with_bike_in_minutes'] = round((nyc_bikes_2022['time_spent_with_bike']/60),2)
nyc_bikes_2022

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,time_spent_with_bike,time_spent_with_bike_in_minutes
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52.000,2022-01-18 08:28:18.000,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,40.692395,-73.993379,member,266,4.43
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22.000,2022-01-21 09:05:44.000,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,40.727408,-73.981420,member,142,2.37
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32.000,2022-01-22 14:53:18.000,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,40.762009,-73.996975,member,1486,24.77
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47.000,2022-01-19 14:54:02.000,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,40.768692,-73.924957,member,255,4.25
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06.000,2022-01-16 14:44:06.000,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,40.696233,-73.991421,member,480,8.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30632313,1F223EDAFF420AE3,electric_bike,2022-12-01 20:26:45.847,2022-12-01 20:30:46.012,Avenue D & E 3 St,5436.09,Stanton St & Chrystie St,5523.02,40.720701,-73.977939,40.722293,-73.991475,member,240,4.00
30632314,CFA5C560ACB73B8E,classic_bike,2022-12-26 13:46:34.237,2022-12-26 13:52:43.900,43 Ave & 47 St,6209.05,39 Ave & 45 St,6401.03,40.744806,-73.917290,40.749478,-73.918265,member,369,6.15
30632315,11C8C5E0DB947B07,classic_bike,2022-12-01 05:56:14.903,2022-12-01 06:06:10.357,Avenue D & E 3 St,5436.09,Bleecker St & Crosby St,5679.08,40.720828,-73.977932,40.726156,-73.995102,member,595,9.92
30632316,5B9B083C534A5964,classic_bike,2022-12-02 11:54:15.871,2022-12-02 12:01:00.747,Montague St & Clinton St,4677.06,Sands St & Jay St,4821.03,40.694271,-73.992327,40.700119,-73.986200,member,404,6.73
30632317,91C286C462F89A50,classic_bike,2022-12-18 13:35:22.574,2022-12-18 13:37:27.193,Montague St & Clinton St,4677.06,Cadman Plaza E & Tillary St,4677.01,40.694271,-73.992327,40.695977,-73.990149,member,124,2.07

In [30]:
# Created two new columns derived from 'ended_at_day_name', 'started_at_day_name'
# Returned the name of day

nyc_bikes_2023['started_at_day_name'] = nyc_bikes_2023['started_at'].dt.day_name()
nyc_bikes_2023['ended_at_day_name'] = nyc_bikes_2023['ended_at'].dt.day_name()
nyc_bikes_2023

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,time_spent_with_bike,time_spent_with_bike_in_minutes,started_at_day_name,ended_at_day_name
0,4A86C1475DCCADA0,classic_bike,2023-01-26 10:53:44.000,2023-01-26 11:05:17.000,E 53 St & Madison Ave,6659.03,Columbus Ave & W 72 St,7175.05,40.759724,-73.973664,40.777057,-73.978985,member,693,11.55,Thursday,Thursday
1,AE02E1FF7E264874,classic_bike,2023-01-04 11:51:54.000,2023-01-04 12:07:09.000,Halsey St & Ralph Ave,4334.02,Clinton Ave & Myrtle Ave,4651.02,40.684970,-73.922755,40.693261,-73.968896,casual,915,15.25,Wednesday,Wednesday
2,D3F9A2A71AD244C6,classic_bike,2023-01-04 17:26:48.000,2023-01-04 17:43:29.000,Bank St & Hudson St,5922.08,W 52 St & 11 Ave,6926.01,40.736566,-74.006092,40.767272,-73.993929,casual,1001,16.68,Wednesday,Wednesday
3,3D48C6F33AFEF329,classic_bike,2023-01-04 08:31:11.000,2023-01-04 08:42:12.000,E 53 St & Madison Ave,6659.03,W 45 St & 8 Ave,6676.02,40.759711,-73.974023,40.759291,-73.988597,member,661,11.02,Wednesday,Wednesday
4,4865926C3D97BA01,electric_bike,2023-01-03 22:15:34.000,2023-01-03 22:30:35.000,Frederick Douglass Blvd & W 112 St,7631.23,Central Park S & 6 Ave,6876.04,40.801694,-73.957145,40.765909,-73.976342,casual,901,15.02,Tuesday,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36157804,ADDC132B2781F4ED,electric_bike,2023-12-17 12:29:57.955,2023-12-17 12:33:43.211,W 76 St & Columbus Ave,7281.09,Amsterdam Ave & W 82 St,7360.1,40.780184,-73.977285,40.785247,-73.976673,member,225,3.75,Sunday,Sunday
36157805,C2A1CE9F5D86CEBC,electric_bike,2023-12-15 12:25:50.809,2023-12-15 12:39:32.176,Fresh Pond Rd & 69 Ave,4945.06,Myrtle Ave & Marcy Ave,4707.03,40.703139,-73.895477,40.695398,-73.949549,member,821,13.68,Friday,Friday
36157806,38A28CE39397CA1E,classic_bike,2023-12-12 17:11:16.792,2023-12-12 17:17:45.781,Ocean Ave & Crooke Ave,3408.05,Lincoln Rd & Ocean Ave,3633.08,40.653260,-73.961720,40.660500,-73.962600,member,388,6.47,Tuesday,Tuesday
36157807,B9C000D3EECE6A8F,electric_bike,2023-12-26 19:10:18.563,2023-12-26 19:14:48.843,Maiden Ln & Pearl St,5065.10,Centre St & Chambers St,5207.01,40.752142,-73.993647,40.712733,-74.004607,member,270,4.50,Tuesday,Tuesday
36157808,D12C9B14AD682510,classic_bike,2023-12-09 16:20:57.967,2023-12-09 16:25:35.530,Lincoln Ave & E 138 St,7744.06,Willis Ave & Bruckner Blvd,7691.05,40.810893,-73.927311,40.805701,-73.925177,member,277,4.62,Saturday,Saturday

In [31]:
nyc_bikes_2022['started_at_day_name'] = nyc_bikes_2022['started_at'].dt.day_name()
nyc_bikes_2022['ended_at_day_name'] = nyc_bikes_2022['ended_at'].dt.day_name()
nyc_bikes_2022

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,time_spent_with_bike,time_spent_with_bike_in_minutes,started_at_day_name,ended_at_day_name
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52.000,2022-01-18 08:28:18.000,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,40.692395,-73.993379,member,266,4.43,Tuesday,Tuesday
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22.000,2022-01-21 09:05:44.000,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,40.727408,-73.981420,member,142,2.37,Friday,Friday
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32.000,2022-01-22 14:53:18.000,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,40.762009,-73.996975,member,1486,24.77,Saturday,Saturday
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47.000,2022-01-19 14:54:02.000,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,40.768692,-73.924957,member,255,4.25,Wednesday,Wednesday
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06.000,2022-01-16 14:44:06.000,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,40.696233,-73.991421,member,480,8.00,Sunday,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30632313,1F223EDAFF420AE3,electric_bike,2022-12-01 20:26:45.847,2022-12-01 20:30:46.012,Avenue D & E 3 St,5436.09,Stanton St & Chrystie St,5523.02,40.720701,-73.977939,40.722293,-73.991475,member,240,4.00,Thursday,Thursday
30632314,CFA5C560ACB73B8E,classic_bike,2022-12-26 13:46:34.237,2022-12-26 13:52:43.900,43 Ave & 47 St,6209.05,39 Ave & 45 St,6401.03,40.744806,-73.917290,40.749478,-73.918265,member,369,6.15,Monday,Monday
30632315,11C8C5E0DB947B07,classic_bike,2022-12-01 05:56:14.903,2022-12-01 06:06:10.357,Avenue D & E 3 St,5436.09,Bleecker St & Crosby St,5679.08,40.720828,-73.977932,40.726156,-73.995102,member,595,9.92,Thursday,Thursday
30632316,5B9B083C534A5964,classic_bike,2022-12-02 11:54:15.871,2022-12-02 12:01:00.747,Montague St & Clinton St,4677.06,Sands St & Jay St,4821.03,40.694271,-73.992327,40.700119,-73.986200,member,404,6.73,Friday,Friday
30632317,91C286C462F89A50,classic_bike,2022-12-18 13:35:22.574,2022-12-18 13:37:27.193,Montague St & Clinton St,4677.06,Cadman Plaza E & Tillary St,4677.01,40.694271,-73.992327,40.695977,-73.990149,member,124,2.07,Sunday,Sunday

In [32]:
# Created two new columns derived from 'ended_at_day_name', 'started_at_day_name'
# Returned the hour of day

nyc_bikes_2023['started_at_hour'] = nyc_bikes_2023['started_at'].dt.hour
nyc_bikes_2023['ended_at_hour'] = nyc_bikes_2023['ended_at'].dt.hour
nyc_bikes_2023

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,time_spent_with_bike,time_spent_with_bike_in_minutes,started_at_day_name,ended_at_day_name,started_at_hour,ended_at_hour
0,4A86C1475DCCADA0,classic_bike,2023-01-26 10:53:44.000,2023-01-26 11:05:17.000,E 53 St & Madison Ave,6659.03,Columbus Ave & W 72 St,7175.05,40.759724,-73.973664,40.777057,-73.978985,member,693,11.55,Thursday,Thursday,10,11
1,AE02E1FF7E264874,classic_bike,2023-01-04 11:51:54.000,2023-01-04 12:07:09.000,Halsey St & Ralph Ave,4334.02,Clinton Ave & Myrtle Ave,4651.02,40.684970,-73.922755,40.693261,-73.968896,casual,915,15.25,Wednesday,Wednesday,11,12
2,D3F9A2A71AD244C6,classic_bike,2023-01-04 17:26:48.000,2023-01-04 17:43:29.000,Bank St & Hudson St,5922.08,W 52 St & 11 Ave,6926.01,40.736566,-74.006092,40.767272,-73.993929,casual,1001,16.68,Wednesday,Wednesday,17,17
3,3D48C6F33AFEF329,classic_bike,2023-01-04 08:31:11.000,2023-01-04 08:42:12.000,E 53 St & Madison Ave,6659.03,W 45 St & 8 Ave,6676.02,40.759711,-73.974023,40.759291,-73.988597,member,661,11.02,Wednesday,Wednesday,8,8
4,4865926C3D97BA01,electric_bike,2023-01-03 22:15:34.000,2023-01-03 22:30:35.000,Frederick Douglass Blvd & W 112 St,7631.23,Central Park S & 6 Ave,6876.04,40.801694,-73.957145,40.765909,-73.976342,casual,901,15.02,Tuesday,Tuesday,22,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36157804,ADDC132B2781F4ED,electric_bike,2023-12-17 12:29:57.955,2023-12-17 12:33:43.211,W 76 St & Columbus Ave,7281.09,Amsterdam Ave & W 82 St,7360.1,40.780184,-73.977285,40.785247,-73.976673,member,225,3.75,Sunday,Sunday,12,12
36157805,C2A1CE9F5D86CEBC,electric_bike,2023-12-15 12:25:50.809,2023-12-15 12:39:32.176,Fresh Pond Rd & 69 Ave,4945.06,Myrtle Ave & Marcy Ave,4707.03,40.703139,-73.895477,40.695398,-73.949549,member,821,13.68,Friday,Friday,12,12
36157806,38A28CE39397CA1E,classic_bike,2023-12-12 17:11:16.792,2023-12-12 17:17:45.781,Ocean Ave & Crooke Ave,3408.05,Lincoln Rd & Ocean Ave,3633.08,40.653260,-73.961720,40.660500,-73.962600,member,388,6.47,Tuesday,Tuesday,17,17
36157807,B9C000D3EECE6A8F,electric_bike,2023-12-26 19:10:18.563,2023-12-26 19:14:48.843,Maiden Ln & Pearl St,5065.10,Centre St & Chambers St,5207.01,40.752142,-73.993647,40.712733,-74.004607,member,270,4.50,Tuesday,Tuesday,19,19
36157808,D12C9B14AD682510,classic_bike,2023-12-09 16:20:57.967,2023-12-09 16:25:35.530,Lincoln Ave & E 138 St,7744.06,Willis Ave & Bruckner Blvd,7691.05,40.810893,-73.927311,40.805701,-73.925177,member,277,4.62,Saturday,Saturday,16,16

In [33]:
nyc_bikes_2022['started_at_hour'] = nyc_bikes_2022['started_at'].dt.hour
nyc_bikes_2022['ended_at_hour'] = nyc_bikes_2022['ended_at'].dt.hour
nyc_bikes_2022

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,time_spent_with_bike,time_spent_with_bike_in_minutes,started_at_day_name,ended_at_day_name,started_at_hour,ended_at_hour
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52.000,2022-01-18 08:28:18.000,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,40.692395,-73.993379,member,266,4.43,Tuesday,Tuesday,8,8
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22.000,2022-01-21 09:05:44.000,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,40.727408,-73.981420,member,142,2.37,Friday,Friday,9,9
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32.000,2022-01-22 14:53:18.000,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,40.762009,-73.996975,member,1486,24.77,Saturday,Saturday,14,14
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47.000,2022-01-19 14:54:02.000,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,40.768692,-73.924957,member,255,4.25,Wednesday,Wednesday,14,14
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06.000,2022-01-16 14:44:06.000,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,40.696233,-73.991421,member,480,8.00,Sunday,Sunday,14,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30632313,1F223EDAFF420AE3,electric_bike,2022-12-01 20:26:45.847,2022-12-01 20:30:46.012,Avenue D & E 3 St,5436.09,Stanton St & Chrystie St,5523.02,40.720701,-73.977939,40.722293,-73.991475,member,240,4.00,Thursday,Thursday,20,20
30632314,CFA5C560ACB73B8E,classic_bike,2022-12-26 13:46:34.237,2022-12-26 13:52:43.900,43 Ave & 47 St,6209.05,39 Ave & 45 St,6401.03,40.744806,-73.917290,40.749478,-73.918265,member,369,6.15,Monday,Monday,13,13
30632315,11C8C5E0DB947B07,classic_bike,2022-12-01 05:56:14.903,2022-12-01 06:06:10.357,Avenue D & E 3 St,5436.09,Bleecker St & Crosby St,5679.08,40.720828,-73.977932,40.726156,-73.995102,member,595,9.92,Thursday,Thursday,5,6
30632316,5B9B083C534A5964,classic_bike,2022-12-02 11:54:15.871,2022-12-02 12:01:00.747,Montague St & Clinton St,4677.06,Sands St & Jay St,4821.03,40.694271,-73.992327,40.700119,-73.986200,member,404,6.73,Friday,Friday,11,12
30632317,91C286C462F89A50,classic_bike,2022-12-18 13:35:22.574,2022-12-18 13:37:27.193,Montague St & Clinton St,4677.06,Cadman Plaza E & Tillary St,4677.01,40.694271,-73.992327,40.695977,-73.990149,member,124,2.07,Sunday,Sunday,13,13

In [34]:
# Created two new columns derived from 'ended_at_day_name', 'started_at_day_name'
# Returned the month of year

nyc_bikes_2023['started_at_month_name'] = nyc_bikes_2023['started_at'].dt.month_name()
nyc_bikes_2023['ended_at_month_name'] = nyc_bikes_2023['ended_at'].dt.month_name()

nyc_bikes_2023

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,end_lng,member_casual,time_spent_with_bike,time_spent_with_bike_in_minutes,started_at_day_name,ended_at_day_name,started_at_hour,ended_at_hour,started_at_month_name,ended_at_month_name
0,4A86C1475DCCADA0,classic_bike,2023-01-26 10:53:44.000,2023-01-26 11:05:17.000,E 53 St & Madison Ave,6659.03,Columbus Ave & W 72 St,7175.05,40.759724,-73.973664,...,-73.978985,member,693,11.55,Thursday,Thursday,10,11,January,January
1,AE02E1FF7E264874,classic_bike,2023-01-04 11:51:54.000,2023-01-04 12:07:09.000,Halsey St & Ralph Ave,4334.02,Clinton Ave & Myrtle Ave,4651.02,40.684970,-73.922755,...,-73.968896,casual,915,15.25,Wednesday,Wednesday,11,12,January,January
2,D3F9A2A71AD244C6,classic_bike,2023-01-04 17:26:48.000,2023-01-04 17:43:29.000,Bank St & Hudson St,5922.08,W 52 St & 11 Ave,6926.01,40.736566,-74.006092,...,-73.993929,casual,1001,16.68,Wednesday,Wednesday,17,17,January,January
3,3D48C6F33AFEF329,classic_bike,2023-01-04 08:31:11.000,2023-01-04 08:42:12.000,E 53 St & Madison Ave,6659.03,W 45 St & 8 Ave,6676.02,40.759711,-73.974023,...,-73.988597,member,661,11.02,Wednesday,Wednesday,8,8,January,January
4,4865926C3D97BA01,electric_bike,2023-01-03 22:15:34.000,2023-01-03 22:30:35.000,Frederick Douglass Blvd & W 112 St,7631.23,Central Park S & 6 Ave,6876.04,40.801694,-73.957145,...,-73.976342,casual,901,15.02,Tuesday,Tuesday,22,22,January,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36157804,ADDC132B2781F4ED,electric_bike,2023-12-17 12:29:57.955,2023-12-17 12:33:43.211,W 76 St & Columbus Ave,7281.09,Amsterdam Ave & W 82 St,7360.1,40.780184,-73.977285,...,-73.976673,member,225,3.75,Sunday,Sunday,12,12,December,December
36157805,C2A1CE9F5D86CEBC,electric_bike,2023-12-15 12:25:50.809,2023-12-15 12:39:32.176,Fresh Pond Rd & 69 Ave,4945.06,Myrtle Ave & Marcy Ave,4707.03,40.703139,-73.895477,...,-73.949549,member,821,13.68,Friday,Friday,12,12,December,December
36157806,38A28CE39397CA1E,classic_bike,2023-12-12 17:11:16.792,2023-12-12 17:17:45.781,Ocean Ave & Crooke Ave,3408.05,Lincoln Rd & Ocean Ave,3633.08,40.653260,-73.961720,...,-73.962600,member,388,6.47,Tuesday,Tuesday,17,17,December,December
36157807,B9C000D3EECE6A8F,electric_bike,2023-12-26 19:10:18.563,2023-12-26 19:14:48.843,Maiden Ln & Pearl St,5065.10,Centre St & Chambers St,5207.01,40.752142,-73.993647,...,-74.004607,member,270,4.50,Tuesday,Tuesday,19,19,December,December
36157808,D12C9B14AD682510,classic_bike,2023-12-09 16:20:57.967,2023-12-09 16:25:35.530,Lincoln Ave & E 138 St,7744.06,Willis Ave & Bruckner Blvd,7691.05,40.810893,-73.927311,...,-73.925177,member,277,4.62,Saturday,Saturday,16,16,December,December

In [35]:
nyc_bikes_2022['started_at_month_name'] = nyc_bikes_2022['started_at'].dt.month_name()
nyc_bikes_2022['ended_at_month_name'] = nyc_bikes_2022['ended_at'].dt.month_name()

nyc_bikes_2022

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,end_lng,member_casual,time_spent_with_bike,time_spent_with_bike_in_minutes,started_at_day_name,ended_at_day_name,started_at_hour,ended_at_hour,started_at_month_name,ended_at_month_name
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52.000,2022-01-18 08:28:18.000,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,...,-73.993379,member,266,4.43,Tuesday,Tuesday,8,8,January,January
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22.000,2022-01-21 09:05:44.000,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,...,-73.981420,member,142,2.37,Friday,Friday,9,9,January,January
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32.000,2022-01-22 14:53:18.000,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,...,-73.996975,member,1486,24.77,Saturday,Saturday,14,14,January,January
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47.000,2022-01-19 14:54:02.000,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,...,-73.924957,member,255,4.25,Wednesday,Wednesday,14,14,January,January
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06.000,2022-01-16 14:44:06.000,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,...,-73.991421,member,480,8.00,Sunday,Sunday,14,14,January,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30632313,1F223EDAFF420AE3,electric_bike,2022-12-01 20:26:45.847,2022-12-01 20:30:46.012,Avenue D & E 3 St,5436.09,Stanton St & Chrystie St,5523.02,40.720701,-73.977939,...,-73.991475,member,240,4.00,Thursday,Thursday,20,20,December,December
30632314,CFA5C560ACB73B8E,classic_bike,2022-12-26 13:46:34.237,2022-12-26 13:52:43.900,43 Ave & 47 St,6209.05,39 Ave & 45 St,6401.03,40.744806,-73.917290,...,-73.918265,member,369,6.15,Monday,Monday,13,13,December,December
30632315,11C8C5E0DB947B07,classic_bike,2022-12-01 05:56:14.903,2022-12-01 06:06:10.357,Avenue D & E 3 St,5436.09,Bleecker St & Crosby St,5679.08,40.720828,-73.977932,...,-73.995102,member,595,9.92,Thursday,Thursday,5,6,December,December
30632316,5B9B083C534A5964,classic_bike,2022-12-02 11:54:15.871,2022-12-02 12:01:00.747,Montague St & Clinton St,4677.06,Sands St & Jay St,4821.03,40.694271,-73.992327,...,-73.986200,member,404,6.73,Friday,Friday,11,12,December,December
30632317,91C286C462F89A50,classic_bike,2022-12-18 13:35:22.574,2022-12-18 13:37:27.193,Montague St & Clinton St,4677.06,Cadman Plaza E & Tillary St,4677.01,40.694271,-73.992327,...,-73.990149,member,124,2.07,Sunday,Sunday,13,13,December,December

In [36]:
# Created two new columns derived from 'ended_at_day_name', 'started_at_day_name'
# Returns year

nyc_bikes_2023['started_at_year'] = nyc_bikes_2023['started_at'].dt.year
nyc_bikes_2023['ended_at_year'] = nyc_bikes_2023['ended_at'].dt.year
nyc_bikes_2023

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,time_spent_with_bike,time_spent_with_bike_in_minutes,started_at_day_name,ended_at_day_name,started_at_hour,ended_at_hour,started_at_month_name,ended_at_month_name,started_at_year,ended_at_year
0,4A86C1475DCCADA0,classic_bike,2023-01-26 10:53:44.000,2023-01-26 11:05:17.000,E 53 St & Madison Ave,6659.03,Columbus Ave & W 72 St,7175.05,40.759724,-73.973664,...,693,11.55,Thursday,Thursday,10,11,January,January,2023,2023
1,AE02E1FF7E264874,classic_bike,2023-01-04 11:51:54.000,2023-01-04 12:07:09.000,Halsey St & Ralph Ave,4334.02,Clinton Ave & Myrtle Ave,4651.02,40.684970,-73.922755,...,915,15.25,Wednesday,Wednesday,11,12,January,January,2023,2023
2,D3F9A2A71AD244C6,classic_bike,2023-01-04 17:26:48.000,2023-01-04 17:43:29.000,Bank St & Hudson St,5922.08,W 52 St & 11 Ave,6926.01,40.736566,-74.006092,...,1001,16.68,Wednesday,Wednesday,17,17,January,January,2023,2023
3,3D48C6F33AFEF329,classic_bike,2023-01-04 08:31:11.000,2023-01-04 08:42:12.000,E 53 St & Madison Ave,6659.03,W 45 St & 8 Ave,6676.02,40.759711,-73.974023,...,661,11.02,Wednesday,Wednesday,8,8,January,January,2023,2023
4,4865926C3D97BA01,electric_bike,2023-01-03 22:15:34.000,2023-01-03 22:30:35.000,Frederick Douglass Blvd & W 112 St,7631.23,Central Park S & 6 Ave,6876.04,40.801694,-73.957145,...,901,15.02,Tuesday,Tuesday,22,22,January,January,2023,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36157804,ADDC132B2781F4ED,electric_bike,2023-12-17 12:29:57.955,2023-12-17 12:33:43.211,W 76 St & Columbus Ave,7281.09,Amsterdam Ave & W 82 St,7360.1,40.780184,-73.977285,...,225,3.75,Sunday,Sunday,12,12,December,December,2023,2023
36157805,C2A1CE9F5D86CEBC,electric_bike,2023-12-15 12:25:50.809,2023-12-15 12:39:32.176,Fresh Pond Rd & 69 Ave,4945.06,Myrtle Ave & Marcy Ave,4707.03,40.703139,-73.895477,...,821,13.68,Friday,Friday,12,12,December,December,2023,2023
36157806,38A28CE39397CA1E,classic_bike,2023-12-12 17:11:16.792,2023-12-12 17:17:45.781,Ocean Ave & Crooke Ave,3408.05,Lincoln Rd & Ocean Ave,3633.08,40.653260,-73.961720,...,388,6.47,Tuesday,Tuesday,17,17,December,December,2023,2023
36157807,B9C000D3EECE6A8F,electric_bike,2023-12-26 19:10:18.563,2023-12-26 19:14:48.843,Maiden Ln & Pearl St,5065.10,Centre St & Chambers St,5207.01,40.752142,-73.993647,...,270,4.50,Tuesday,Tuesday,19,19,December,December,2023,2023
36157808,D12C9B14AD682510,classic_bike,2023-12-09 16:20:57.967,2023-12-09 16:25:35.530,Lincoln Ave & E 138 St,7744.06,Willis Ave & Bruckner Blvd,7691.05,40.810893,-73.927311,...,277,4.62,Saturday,Saturday,16,16,December,December,2023,2023

In [37]:
nyc_bikes_2022['started_at_year'] = nyc_bikes_2022['started_at'].dt.year
nyc_bikes_2022['ended_at_year'] = nyc_bikes_2022['ended_at'].dt.year
nyc_bikes_2022

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,time_spent_with_bike,time_spent_with_bike_in_minutes,started_at_day_name,ended_at_day_name,started_at_hour,ended_at_hour,started_at_month_name,ended_at_month_name,started_at_year,ended_at_year
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52.000,2022-01-18 08:28:18.000,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,...,266,4.43,Tuesday,Tuesday,8,8,January,January,2022,2022
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22.000,2022-01-21 09:05:44.000,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,...,142,2.37,Friday,Friday,9,9,January,January,2022,2022
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32.000,2022-01-22 14:53:18.000,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,...,1486,24.77,Saturday,Saturday,14,14,January,January,2022,2022
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47.000,2022-01-19 14:54:02.000,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,...,255,4.25,Wednesday,Wednesday,14,14,January,January,2022,2022
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06.000,2022-01-16 14:44:06.000,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,...,480,8.00,Sunday,Sunday,14,14,January,January,2022,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30632313,1F223EDAFF420AE3,electric_bike,2022-12-01 20:26:45.847,2022-12-01 20:30:46.012,Avenue D & E 3 St,5436.09,Stanton St & Chrystie St,5523.02,40.720701,-73.977939,...,240,4.00,Thursday,Thursday,20,20,December,December,2022,2022
30632314,CFA5C560ACB73B8E,classic_bike,2022-12-26 13:46:34.237,2022-12-26 13:52:43.900,43 Ave & 47 St,6209.05,39 Ave & 45 St,6401.03,40.744806,-73.917290,...,369,6.15,Monday,Monday,13,13,December,December,2022,2022
30632315,11C8C5E0DB947B07,classic_bike,2022-12-01 05:56:14.903,2022-12-01 06:06:10.357,Avenue D & E 3 St,5436.09,Bleecker St & Crosby St,5679.08,40.720828,-73.977932,...,595,9.92,Thursday,Thursday,5,6,December,December,2022,2022
30632316,5B9B083C534A5964,classic_bike,2022-12-02 11:54:15.871,2022-12-02 12:01:00.747,Montague St & Clinton St,4677.06,Sands St & Jay St,4821.03,40.694271,-73.992327,...,404,6.73,Friday,Friday,11,12,December,December,2022,2022
30632317,91C286C462F89A50,classic_bike,2022-12-18 13:35:22.574,2022-12-18 13:37:27.193,Montague St & Clinton St,4677.06,Cadman Plaza E & Tillary St,4677.01,40.694271,-73.992327,...,124,2.07,Sunday,Sunday,13,13,December,December,2022,2022

In [38]:
# Created two new columns derived from 'ended_at_day_name', 'started_at_day_name'
# Returned the year-month-day

nyc_bikes_2023['started_at_date'] = nyc_bikes_2023['started_at'].dt.to_period('D')
nyc_bikes_2023['ended_at_date'] = nyc_bikes_2023['ended_at'].dt.to_period('D')
nyc_bikes_2023

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,started_at_day_name,ended_at_day_name,started_at_hour,ended_at_hour,started_at_month_name,ended_at_month_name,started_at_year,ended_at_year,started_at_date,ended_at_date
0,4A86C1475DCCADA0,classic_bike,2023-01-26 10:53:44.000,2023-01-26 11:05:17.000,E 53 St & Madison Ave,6659.03,Columbus Ave & W 72 St,7175.05,40.759724,-73.973664,...,Thursday,Thursday,10,11,January,January,2023,2023,2023-01-26,2023-01-26
1,AE02E1FF7E264874,classic_bike,2023-01-04 11:51:54.000,2023-01-04 12:07:09.000,Halsey St & Ralph Ave,4334.02,Clinton Ave & Myrtle Ave,4651.02,40.684970,-73.922755,...,Wednesday,Wednesday,11,12,January,January,2023,2023,2023-01-04,2023-01-04
2,D3F9A2A71AD244C6,classic_bike,2023-01-04 17:26:48.000,2023-01-04 17:43:29.000,Bank St & Hudson St,5922.08,W 52 St & 11 Ave,6926.01,40.736566,-74.006092,...,Wednesday,Wednesday,17,17,January,January,2023,2023,2023-01-04,2023-01-04
3,3D48C6F33AFEF329,classic_bike,2023-01-04 08:31:11.000,2023-01-04 08:42:12.000,E 53 St & Madison Ave,6659.03,W 45 St & 8 Ave,6676.02,40.759711,-73.974023,...,Wednesday,Wednesday,8,8,January,January,2023,2023,2023-01-04,2023-01-04
4,4865926C3D97BA01,electric_bike,2023-01-03 22:15:34.000,2023-01-03 22:30:35.000,Frederick Douglass Blvd & W 112 St,7631.23,Central Park S & 6 Ave,6876.04,40.801694,-73.957145,...,Tuesday,Tuesday,22,22,January,January,2023,2023,2023-01-03,2023-01-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36157804,ADDC132B2781F4ED,electric_bike,2023-12-17 12:29:57.955,2023-12-17 12:33:43.211,W 76 St & Columbus Ave,7281.09,Amsterdam Ave & W 82 St,7360.1,40.780184,-73.977285,...,Sunday,Sunday,12,12,December,December,2023,2023,2023-12-17,2023-12-17
36157805,C2A1CE9F5D86CEBC,electric_bike,2023-12-15 12:25:50.809,2023-12-15 12:39:32.176,Fresh Pond Rd & 69 Ave,4945.06,Myrtle Ave & Marcy Ave,4707.03,40.703139,-73.895477,...,Friday,Friday,12,12,December,December,2023,2023,2023-12-15,2023-12-15
36157806,38A28CE39397CA1E,classic_bike,2023-12-12 17:11:16.792,2023-12-12 17:17:45.781,Ocean Ave & Crooke Ave,3408.05,Lincoln Rd & Ocean Ave,3633.08,40.653260,-73.961720,...,Tuesday,Tuesday,17,17,December,December,2023,2023,2023-12-12,2023-12-12
36157807,B9C000D3EECE6A8F,electric_bike,2023-12-26 19:10:18.563,2023-12-26 19:14:48.843,Maiden Ln & Pearl St,5065.10,Centre St & Chambers St,5207.01,40.752142,-73.993647,...,Tuesday,Tuesday,19,19,December,December,2023,2023,2023-12-26,2023-12-26
36157808,D12C9B14AD682510,classic_bike,2023-12-09 16:20:57.967,2023-12-09 16:25:35.530,Lincoln Ave & E 138 St,7744.06,Willis Ave & Bruckner Blvd,7691.05,40.810893,-73.927311,...,Saturday,Saturday,16,16,December,December,2023,2023,2023-12-09,2023-12-09

In [39]:
nyc_bikes_2022['started_at_date'] = nyc_bikes_2022['started_at'].dt.to_period('D')
nyc_bikes_2022['ended_at_date'] = nyc_bikes_2022['ended_at'].dt.to_period('D')
nyc_bikes_2022

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,started_at_day_name,ended_at_day_name,started_at_hour,ended_at_hour,started_at_month_name,ended_at_month_name,started_at_year,ended_at_year,started_at_date,ended_at_date
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52.000,2022-01-18 08:28:18.000,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,...,Tuesday,Tuesday,8,8,January,January,2022,2022,2022-01-18,2022-01-18
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22.000,2022-01-21 09:05:44.000,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,...,Friday,Friday,9,9,January,January,2022,2022,2022-01-21,2022-01-21
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32.000,2022-01-22 14:53:18.000,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,...,Saturday,Saturday,14,14,January,January,2022,2022,2022-01-22,2022-01-22
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47.000,2022-01-19 14:54:02.000,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,...,Wednesday,Wednesday,14,14,January,January,2022,2022,2022-01-19,2022-01-19
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06.000,2022-01-16 14:44:06.000,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,...,Sunday,Sunday,14,14,January,January,2022,2022,2022-01-16,2022-01-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30632313,1F223EDAFF420AE3,electric_bike,2022-12-01 20:26:45.847,2022-12-01 20:30:46.012,Avenue D & E 3 St,5436.09,Stanton St & Chrystie St,5523.02,40.720701,-73.977939,...,Thursday,Thursday,20,20,December,December,2022,2022,2022-12-01,2022-12-01
30632314,CFA5C560ACB73B8E,classic_bike,2022-12-26 13:46:34.237,2022-12-26 13:52:43.900,43 Ave & 47 St,6209.05,39 Ave & 45 St,6401.03,40.744806,-73.917290,...,Monday,Monday,13,13,December,December,2022,2022,2022-12-26,2022-12-26
30632315,11C8C5E0DB947B07,classic_bike,2022-12-01 05:56:14.903,2022-12-01 06:06:10.357,Avenue D & E 3 St,5436.09,Bleecker St & Crosby St,5679.08,40.720828,-73.977932,...,Thursday,Thursday,5,6,December,December,2022,2022,2022-12-01,2022-12-01
30632316,5B9B083C534A5964,classic_bike,2022-12-02 11:54:15.871,2022-12-02 12:01:00.747,Montague St & Clinton St,4677.06,Sands St & Jay St,4821.03,40.694271,-73.992327,...,Friday,Friday,11,12,December,December,2022,2022,2022-12-02,2022-12-02
30632317,91C286C462F89A50,classic_bike,2022-12-18 13:35:22.574,2022-12-18 13:37:27.193,Montague St & Clinton St,4677.06,Cadman Plaza E & Tillary St,4677.01,40.694271,-73.992327,...,Sunday,Sunday,13,13,December,December,2022,2022,2022-12-18,2022-12-18

# 7) Filtering out outliers and rides longer than 2 hrs (120 minutes)

In [40]:
# Statistical description of dataframe
# Unusually the bike ride lasts over 50000 minutes
# There is a monetary penalty for rides longer than 45 minutes for members and 30 minutes for casual customers
# It is less likely that any citi bike ride would take several hours
# The System host site indicates that for distance calculation, trips are capped at a 2 hour (120 minutes) limit
# It is highly probable that the bike was not engaged properly at the returning station

nyc_bikes_2023.describe()

,start_lat,start_lng,end_lat,end_lng,time_spent_with_bike,time_spent_with_bike_in_minutes,started_at_hour,ended_at_hour,started_at_year,ended_at_year
count,3.604889e+07,3.604889e+07,3.604870e+07,3.604870e+07,3.604889e+07,3.604889e+07,3.604889e+07,3.604889e+07,36048890.0,36048890.0
mean,4.074019e+01,-7.397262e+01,4.074004e+01,-7.397269e+01,8.111374e+02,1.351896e+01,1.406948e+01,1.418593e+01,2023.0,2023.0
std,4.087415e-02,2.801094e-02,4.085053e-02,2.802210e-02,1.700970e+03,2.834951e+01,5.048179e+00,5.108091e+00,0.0,0.0
min,4.057483e+01,-7.407222e+01,4.063338e+01,-7.408670e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2023.0,2023.0
25%,4.071503e+01,-7.399253e+01,4.071495e+01,-7.399266e+01,3.010000e+02,5.020000e+00,1.000000e+01,1.000000e+01,2023.0,2023.0
50%,4.073913e+01,-7.398017e+01,4.073902e+01,-7.398017e+01,5.420000e+02,9.030000e+00,1.500000e+01,1.500000e+01,2023.0,2023.0
75%,4.076328e+01,-7.395587e+01,4.076315e+01,-7.395593e+01,9.670000e+02,1.612000e+01,1.800000e+01,1.800000e+01,2023.0,2023.0
max,4.089416e+01,-7.379639e+01,4.088630e+01,-7.384978e+01,9.303770e+05,1.550628e+04,2.300000e+01,2.300000e+01,2023.0,2023.0

In [41]:
nyc_bikes_2022.describe()

,start_lat,start_lng,end_lat,end_lng,time_spent_with_bike,time_spent_with_bike_in_minutes,started_at_hour,ended_at_hour,started_at_year,ended_at_year
count,3.056100e+07,3.056100e+07,3.056100e+07,3.056100e+07,3.056100e+07,3.056100e+07,3.056100e+07,3.056100e+07,3.056100e+07,30560997.0
mean,4.074084e+01,-7.397513e+01,4.074062e+01,-7.397523e+01,9.152299e+02,1.525383e+01,1.406613e+01,1.419323e+01,2.022000e+03,2022.0
std,3.909937e-02,2.594231e-02,3.904366e-02,2.595979e-02,1.189288e+04,1.982146e+02,5.029508e+00,5.094368e+00,2.558181e-04,0.0
min,4.062737e+01,-7.402802e+01,4.063338e+01,-7.408670e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.021000e+03,2022.0
25%,4.071606e+01,-7.399379e+01,4.071606e+01,-7.399380e+01,3.290000e+02,5.480000e+00,1.000000e+01,1.100000e+01,2.022000e+03,2022.0
50%,4.073945e+01,-7.398163e+01,4.073932e+01,-7.398166e+01,5.920000e+02,9.870000e+00,1.500000e+01,1.500000e+01,2.022000e+03,2022.0
75%,4.076341e+01,-7.395922e+01,4.076319e+01,-7.395922e+01,1.056000e+03,1.760000e+01,1.800000e+01,1.800000e+01,2.022000e+03,2022.0
max,4.088398e+01,-7.387859e+01,4.088226e+01,-7.388145e+01,4.456526e+07,7.427543e+05,2.300000e+01,2.300000e+01,2.022000e+03,2022.0

In [42]:
# We will filter out any trips greater than 2 hours (120 minutes) and any values expressed as negative numbers
nyc_bikes_2023 = nyc_bikes_2023[(nyc_bikes_2023['time_spent_with_bike_in_minutes']<=120) & (nyc_bikes_2023['time_spent_with_bike_in_minutes']>=0)]
nyc_bikes_2023

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,started_at_day_name,ended_at_day_name,started_at_hour,ended_at_hour,started_at_month_name,ended_at_month_name,started_at_year,ended_at_year,started_at_date,ended_at_date
0,4A86C1475DCCADA0,classic_bike,2023-01-26 10:53:44.000,2023-01-26 11:05:17.000,E 53 St & Madison Ave,6659.03,Columbus Ave & W 72 St,7175.05,40.759724,-73.973664,...,Thursday,Thursday,10,11,January,January,2023,2023,2023-01-26,2023-01-26
1,AE02E1FF7E264874,classic_bike,2023-01-04 11:51:54.000,2023-01-04 12:07:09.000,Halsey St & Ralph Ave,4334.02,Clinton Ave & Myrtle Ave,4651.02,40.684970,-73.922755,...,Wednesday,Wednesday,11,12,January,January,2023,2023,2023-01-04,2023-01-04
2,D3F9A2A71AD244C6,classic_bike,2023-01-04 17:26:48.000,2023-01-04 17:43:29.000,Bank St & Hudson St,5922.08,W 52 St & 11 Ave,6926.01,40.736566,-74.006092,...,Wednesday,Wednesday,17,17,January,January,2023,2023,2023-01-04,2023-01-04
3,3D48C6F33AFEF329,classic_bike,2023-01-04 08:31:11.000,2023-01-04 08:42:12.000,E 53 St & Madison Ave,6659.03,W 45 St & 8 Ave,6676.02,40.759711,-73.974023,...,Wednesday,Wednesday,8,8,January,January,2023,2023,2023-01-04,2023-01-04
4,4865926C3D97BA01,electric_bike,2023-01-03 22:15:34.000,2023-01-03 22:30:35.000,Frederick Douglass Blvd & W 112 St,7631.23,Central Park S & 6 Ave,6876.04,40.801694,-73.957145,...,Tuesday,Tuesday,22,22,January,January,2023,2023,2023-01-03,2023-01-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36157804,ADDC132B2781F4ED,electric_bike,2023-12-17 12:29:57.955,2023-12-17 12:33:43.211,W 76 St & Columbus Ave,7281.09,Amsterdam Ave & W 82 St,7360.1,40.780184,-73.977285,...,Sunday,Sunday,12,12,December,December,2023,2023,2023-12-17,2023-12-17
36157805,C2A1CE9F5D86CEBC,electric_bike,2023-12-15 12:25:50.809,2023-12-15 12:39:32.176,Fresh Pond Rd & 69 Ave,4945.06,Myrtle Ave & Marcy Ave,4707.03,40.703139,-73.895477,...,Friday,Friday,12,12,December,December,2023,2023,2023-12-15,2023-12-15
36157806,38A28CE39397CA1E,classic_bike,2023-12-12 17:11:16.792,2023-12-12 17:17:45.781,Ocean Ave & Crooke Ave,3408.05,Lincoln Rd & Ocean Ave,3633.08,40.653260,-73.961720,...,Tuesday,Tuesday,17,17,December,December,2023,2023,2023-12-12,2023-12-12
36157807,B9C000D3EECE6A8F,electric_bike,2023-12-26 19:10:18.563,2023-12-26 19:14:48.843,Maiden Ln & Pearl St,5065.10,Centre St & Chambers St,5207.01,40.752142,-73.993647,...,Tuesday,Tuesday,19,19,December,December,2023,2023,2023-12-26,2023-12-26
36157808,D12C9B14AD682510,classic_bike,2023-12-09 16:20:57.967,2023-12-09 16:25:35.530,Lincoln Ave & E 138 St,7744.06,Willis Ave & Bruckner Blvd,7691.05,40.810893,-73.927311,...,Saturday,Saturday,16,16,December,December,2023,2023,2023-12-09,2023-12-09

In [43]:
nyc_bikes_2022 = nyc_bikes_2022[(nyc_bikes_2022['time_spent_with_bike_in_minutes']<=120) & (nyc_bikes_2022['time_spent_with_bike_in_minutes']>=0)]
nyc_bikes_2022

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,started_at_day_name,ended_at_day_name,started_at_hour,ended_at_hour,started_at_month_name,ended_at_month_name,started_at_year,ended_at_year,started_at_date,ended_at_date
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52.000,2022-01-18 08:28:18.000,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,...,Tuesday,Tuesday,8,8,January,January,2022,2022,2022-01-18,2022-01-18
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22.000,2022-01-21 09:05:44.000,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,...,Friday,Friday,9,9,January,January,2022,2022,2022-01-21,2022-01-21
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32.000,2022-01-22 14:53:18.000,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,...,Saturday,Saturday,14,14,January,January,2022,2022,2022-01-22,2022-01-22
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47.000,2022-01-19 14:54:02.000,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,...,Wednesday,Wednesday,14,14,January,January,2022,2022,2022-01-19,2022-01-19
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06.000,2022-01-16 14:44:06.000,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,...,Sunday,Sunday,14,14,January,January,2022,2022,2022-01-16,2022-01-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30632313,1F223EDAFF420AE3,electric_bike,2022-12-01 20:26:45.847,2022-12-01 20:30:46.012,Avenue D & E 3 St,5436.09,Stanton St & Chrystie St,5523.02,40.720701,-73.977939,...,Thursday,Thursday,20,20,December,December,2022,2022,2022-12-01,2022-12-01
30632314,CFA5C560ACB73B8E,classic_bike,2022-12-26 13:46:34.237,2022-12-26 13:52:43.900,43 Ave & 47 St,6209.05,39 Ave & 45 St,6401.03,40.744806,-73.917290,...,Monday,Monday,13,13,December,December,2022,2022,2022-12-26,2022-12-26
30632315,11C8C5E0DB947B07,classic_bike,2022-12-01 05:56:14.903,2022-12-01 06:06:10.357,Avenue D & E 3 St,5436.09,Bleecker St & Crosby St,5679.08,40.720828,-73.977932,...,Thursday,Thursday,5,6,December,December,2022,2022,2022-12-01,2022-12-01
30632316,5B9B083C534A5964,classic_bike,2022-12-02 11:54:15.871,2022-12-02 12:01:00.747,Montague St & Clinton St,4677.06,Sands St & Jay St,4821.03,40.694271,-73.992327,...,Friday,Friday,11,12,December,December,2022,2022,2022-12-02,2022-12-02
30632317,91C286C462F89A50,classic_bike,2022-12-18 13:35:22.574,2022-12-18 13:37:27.193,Montague St & Clinton St,4677.06,Cadman Plaza E & Tillary St,4677.01,40.694271,-73.992327,...,Sunday,Sunday,13,13,December,December,2022,2022,2022-12-18,2022-12-18

# 8) Rearranging Columns and Exporting Finalized Dataframe to Desktop

In [44]:
# Returning the name of all columns of dataframe

nyc_bikes_2023.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual', 'time_spent_with_bike',
       'time_spent_with_bike_in_minutes', 'started_at_day_name',
       'ended_at_day_name', 'started_at_hour', 'ended_at_hour',
       'started_at_month_name', 'ended_at_month_name', 'started_at_year',
       'ended_at_year', 'started_at_date', 'ended_at_date'],
      dtype='object')

In [45]:
nyc_bikes_2022.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual', 'time_spent_with_bike',
       'time_spent_with_bike_in_minutes', 'started_at_day_name',
       'ended_at_day_name', 'started_at_hour', 'ended_at_hour',
       'started_at_month_name', 'ended_at_month_name', 'started_at_year',
       'ended_at_year', 'started_at_date', 'ended_at_date'],
      dtype='object')

In [46]:
# Selected and rearranged several columns for dataframe

nyc_bikes_2023 = nyc_bikes_2023[['rideable_type', 'member_casual', 'started_at_date', 'started_at_year', 'started_at_month_name', 
                       'started_at_day_name', 'started_at_hour', 'time_spent_with_bike_in_minutes', 'end_station_name', 
                       'end_lat', 'end_lng']]
nyc_bikes_2023

,rideable_type,member_casual,started_at_date,started_at_year,started_at_month_name,started_at_day_name,started_at_hour,time_spent_with_bike_in_minutes,end_station_name,end_lat,end_lng
0,classic_bike,member,2023-01-26,2023,January,Thursday,10,11.55,Columbus Ave & W 72 St,40.777057,-73.978985
1,classic_bike,casual,2023-01-04,2023,January,Wednesday,11,15.25,Clinton Ave & Myrtle Ave,40.693261,-73.968896
2,classic_bike,casual,2023-01-04,2023,January,Wednesday,17,16.68,W 52 St & 11 Ave,40.767272,-73.993929
3,classic_bike,member,2023-01-04,2023,January,Wednesday,8,11.02,W 45 St & 8 Ave,40.759291,-73.988597
4,electric_bike,casual,2023-01-03,2023,January,Tuesday,22,15.02,Central Park S & 6 Ave,40.765909,-73.976342
...,...,...,...,...,...,...,...,...,...,...,...
36157804,electric_bike,member,2023-12-17,2023,December,Sunday,12,3.75,Amsterdam Ave & W 82 St,40.785247,-73.976673
36157805,electric_bike,member,2023-12-15,2023,December,Friday,12,13.68,Myrtle Ave & Marcy Ave,40.695398,-73.949549
36157806,classic_bike,member,2023-12-12,2023,December,Tuesday,17,6.47,Lincoln Rd & Ocean Ave,40.660500,-73.962600
36157807,electric_bike,member,2023-12-26,2023,December,Tuesday,19,4.50,Centre St & Chambers St,40.712733,-74.004607
36157808,classic_bike,member,2023-12-09,2023,December,Saturday,16,4.62,Willis Ave & Bruckner Blvd,40.805701,-73.925177

In [47]:
nyc_bikes_2022 = nyc_bikes_2022[['rideable_type', 'member_casual', 'started_at_date', 'started_at_year', 'started_at_month_name', 
                       'started_at_day_name', 'started_at_hour', 'time_spent_with_bike_in_minutes', 'end_station_name', 
                       'end_lat', 'end_lng']]
nyc_bikes_2022

,rideable_type,member_casual,started_at_date,started_at_year,started_at_month_name,started_at_day_name,started_at_hour,time_spent_with_bike_in_minutes,end_station_name,end_lat,end_lng
0,classic_bike,member,2022-01-18,2022,January,Tuesday,8,4.43,Clinton St & Joralemon St,40.692395,-73.993379
1,classic_bike,member,2022-01-21,2022,January,Friday,9,2.37,E 10 St & Avenue A,40.727408,-73.981420
2,classic_bike,member,2022-01-22,2022,January,Saturday,14,24.77,W 44 St & 11 Ave,40.762009,-73.996975
3,electric_bike,member,2022-01-19,2022,January,Wednesday,14,4.25,Crescent St & 30 Ave,40.768692,-73.924957
4,electric_bike,member,2022-01-16,2022,January,Sunday,14,8.00,Clinton St & Tillary St,40.696233,-73.991421
...,...,...,...,...,...,...,...,...,...,...,...
30632313,electric_bike,member,2022-12-01,2022,December,Thursday,20,4.00,Stanton St & Chrystie St,40.722293,-73.991475
30632314,classic_bike,member,2022-12-26,2022,December,Monday,13,6.15,39 Ave & 45 St,40.749478,-73.918265
30632315,classic_bike,member,2022-12-01,2022,December,Thursday,5,9.92,Bleecker St & Crosby St,40.726156,-73.995102
30632316,classic_bike,member,2022-12-02,2022,December,Friday,11,6.73,Sands St & Jay St,40.700119,-73.986200
30632317,classic_bike,member,2022-12-18,2022,December,Sunday,13,2.07,Cadman Plaza E & Tillary St,40.695977,-73.990149

In [48]:
# Exporting finalized dataframes

nyc_bikes_2022.to_csv(os.path.join(path, 'Desktop', 'bikes_2022-2023.csv'))
nyc_bikes_2023.to_csv(os.path.join(path, 'Desktop', 'bikes_2023-2024.csv'))