# 1) Importing Libraries and DataFrame

In [1]:
# Importing libraries

import pandas as pd
import numpy as np
import os
from datetime import datetime

In [2]:
# Importing dataframe dated 12/22 for nyc

path = r'/Users/matthewabrams'
nyc_bikes_202212 = pd.read_csv(os.path.join(path, 'Downloads', '202212-citibike-tripdata.csv'), index_col = False)
nyc_bikes_202212

/Users/matthewabrams/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (5,7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,0EF496F342AD4E7E,classic_bike,2022-12-05 17:47:32,2022-12-05 18:13:10,DeKalb Ave & Hudson Ave,4513.06,Perry St & Bleecker St,5922.07,40.689909,-73.980552,40.735354,-74.004831,member
1,4B9482CBC3FAC46B,classic_bike,2022-12-08 19:08:05,2022-12-08 19:20:23,E 128 St & Madison Ave,7735.23,E 142 St & 3 Ave,7781.10,40.807518,-73.939027,40.812735,-73.923697,member
2,59F23FEB16138E43,classic_bike,2022-12-22 19:11:48,2022-12-22 19:21:46,E 128 St & Madison Ave,7735.23,E 142 St & 3 Ave,7781.10,40.807569,-73.939101,40.812735,-73.923697,member
3,974F8AE1F18859F4,classic_bike,2022-12-12 08:38:09,2022-12-12 08:43:43,Driggs Ave & N Henry St,5542.04,Meserole Ave & Manhattan Ave,5666.04,40.723208,-73.943045,40.727086,-73.952991,casual
4,4B04C5C25EC9D6ED,classic_bike,2022-12-13 12:29:54,2022-12-13 12:36:35,3 St & 3 Ave,4028.03,Carroll St & 6 Ave,4019.06,40.675070,-73.987752,40.674089,-73.978728,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1649647,CB2EE50F60A58C7B,classic_bike,2022-12-12 08:38:46,2022-12-12 08:46:12,E 41 St & Madison Ave (SW corner),6474.12,6 Ave & W 33 St,6364.07,40.752165,-73.979922,40.749013,-73.988484,member
1649648,3C0DF3280FEB1350,classic_bike,2022-12-12 13:06:32,2022-12-12 13:19:58,Peck Slip & South St,5096.12,Vesey St & Church St,5216.06,40.707689,-74.001254,40.712220,-74.010472,member
1649649,B916E63B630D5020,classic_bike,2022-12-18 01:15:22,2022-12-18 01:48:15,E 41 St & Madison Ave (SW corner),6474.12,Lenox Ave & W 111 St,7602.05,40.752399,-73.980150,40.798786,-73.952300,member
1649650,21EAC007BE7D4161,classic_bike,2022-12-08 23:09:54,2022-12-08 23:26:37,W 37 St & 10 Ave,6611.02,W 70 St & Amsterdam Ave,7207.08,40.756604,-73.997901,40.777480,-73.982886,member
1649651,538408C4A16F4415,electric_bike,2022-12-21 07:26:14,2022-12-21 07:31:40,W 37 St & 10 Ave,6611.02,6 Ave & W 33 St,6364.07,40.756604,-73.997901,40.749013,-73.988484,member

In [3]:
# Importing dataframe dated 11/22 for nyc

nyc_bikes_202211 = pd.read_csv(os.path.join(path, 'Downloads', '202211-citibike-tripdata.csv'), index_col = False)
nyc_bikes_202211

/Users/matthewabrams/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (5,7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,211A73DFC6752EFC,classic_bike,2022-11-30 21:36:23,2022-11-30 21:49:31,2 Ave & E 29 St,6122.09,Pitt St & Stanton St,5406.04,40.741724,-73.978093,40.719261,-73.981780,member
1,568E7F54B3EFB8C3,classic_bike,2022-11-20 11:06:30,2022-11-20 11:17:18,E 97 St & Madison Ave,7393.09,E 74 St & 1 Ave,6953.08,40.787826,-73.953423,40.768974,-73.954823,member
2,0ED37DE3609F47A1,classic_bike,2022-11-17 09:48:34,2022-11-17 09:56:14,E 97 St & Madison Ave,7393.09,Adam Clayton Powell Blvd & W 118 St,7670.09,40.787899,-73.953396,40.804372,-73.951475,member
3,AF0F9BAB2B4AA126,classic_bike,2022-11-02 12:23:36,2022-11-02 12:26:35,Morningside Ave & W 123 St,7741.01,Adam Clayton Powell Blvd & W 118 St,7670.09,40.809931,-73.955209,40.804372,-73.951475,member
4,215FF85772BA2D2B,classic_bike,2022-11-07 16:46:20,2022-11-07 16:54:16,2 Ave & E 29 St,6122.09,W 13 St & 5 Ave,5947.04,40.741803,-73.978004,40.735445,-73.994310,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2460100,AF0FE64934F2F2FA,classic_bike,2022-11-12 09:57:24,2022-11-12 10:22:05,E 75 St & 3 Ave,6991.12,12 Ave & W 40 St,6765.01,40.771129,-73.957723,40.760875,-74.002777,casual
2460101,8173C49CE0822847,classic_bike,2022-11-01 16:33:08,2022-11-01 16:42:29,Verona Pl & Fulton St,4124.04,Dean St & Franklin Ave,4107.13,40.680356,-73.947679,40.677592,-73.955637,casual
2460102,E1764A36071338B6,classic_bike,2022-11-24 12:28:59,2022-11-24 12:33:56,30 Ave & 41 St,6812.06,31 St & Newtown Ave,6923.20,40.763422,-73.914142,40.767549,-73.920933,member
2460103,77D09FB5866F29B8,classic_bike,2022-11-08 10:50:13,2022-11-08 11:09:42,Jay St & York St,4895.09,Lincoln Pl & Classon Ave,3960.01,40.701214,-73.986726,40.672168,-73.960900,member
2460104,4BF983641958B6F7,classic_bike,2022-11-13 13:03:13,2022-11-13 13:09:27,Harman St & Seneca Ave,5002.09,Wyckoff Ave & Gates Ave,4847.03,40.705770,-73.912920,40.699871,-73.911719,member

In [4]:
# Importing dataframe dated 10/22 for nyc

path = r'/Users/matthewabrams'
nyc_bikes_202210 = pd.read_csv(os.path.join(path, 'Downloads', '202210-citibike-tripdata.csv'), index_col = False)
nyc_bikes_202210

/Users/matthewabrams/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (5,7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,2CF35A89B21C6E3C,classic_bike,2022-10-24 14:30:25,2022-10-24 14:37:35,St. Nicholas Ave & W 126 St,7756.10,Amsterdam Ave & W 136 St,7920.05,40.811388,-73.951995,40.819746,-73.951819,member
1,291CC2C6D361C2DA,classic_bike,2022-10-30 03:53:38,2022-10-30 03:57:57,Stuyvesant Ave & Gates Ave,4458.06,Halsey St & Tompkins Ave,4319.07,40.688445,-73.933195,40.682369,-73.944118,member
2,80192DC8429B07EE,classic_bike,2022-10-08 15:03:06,2022-10-08 15:17:13,Broadway & Berry St,5164.05,Meserole Ave & Manhattan Ave,5666.04,40.710361,-73.965304,40.727086,-73.952991,member
3,D214E550C317C65E,classic_bike,2022-10-18 08:32:04,2022-10-18 08:36:41,W 84 St & Columbus Ave,7382.04,W 76 St & Columbus Ave,7281.09,40.785000,-73.972834,40.780184,-73.977285,member
4,2D23E8BAE75AA184,classic_bike,2022-10-26 08:00:40,2022-10-26 08:10:27,Pike St & Monroe St,5159.04,Broad St & Bridge St,4962.08,40.711731,-73.991930,40.703652,-74.011678,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3021665,EB791C76AD3E012D,classic_bike,2022-10-20 11:13:29,2022-10-20 11:23:26,Clinton St & Union St,4266.03,3 St & 3 Ave,4028.03,40.683116,-73.997853,40.675070,-73.987752,member
3021666,B57BDF2A6FA4BA26,classic_bike,2022-10-10 18:36:52,2022-10-10 18:59:03,E 35 St & Madison Ave,6398.08,Central Park West & W 68 St,7079.06,40.748480,-73.982556,40.773407,-73.977825,member
3021667,412A5ADB8EE05B8D,classic_bike,2022-10-25 18:19:19,2022-10-25 18:35:42,Nassau St\t& Duffield St,4781.05,West St & Liberty St,5184.08,40.698374,-73.983878,40.711444,-74.014847,member
3021668,FB3AA7F68A0489ED,classic_bike,2022-10-30 13:53:08,2022-10-30 13:55:52,21 St & Hoyt Ave S,7126.01,24 Ave & 26 St,7152.1,40.774751,-73.923553,40.774591,-73.918544,member
3021669,91177E95D3937743,classic_bike,2022-10-26 16:56:11,2022-10-26 17:01:28,Park Pl & Church St,5288.08,West St & Liberty St,5184.08,40.713342,-74.009355,40.711444,-74.014847,member

In [5]:
# Importing dataframe dated 09/22 for nyc

path = r'/Users/matthewabrams'
nyc_bikes_202209 = pd.read_csv(os.path.join(path, 'Downloads', '202209-citibike-tripdata.csv'), index_col = False)
nyc_bikes_202209

/Users/matthewabrams/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (5,7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,42B9E1161E021F66,classic_bike,2022-09-17 16:06:45,2022-09-17 16:18:03,Henry St & Degraw St,4380.08,7 Ave & Park Pl,4125.07,40.684736,-73.999088,40.677615,-73.973243,member
1,FE5FB109CA0FB68B,classic_bike,2022-09-25 14:26:25,2022-09-25 14:39:43,6 Ave & W 34 St,6364.1,W 50 St & 9 Ave,6854.05,40.749640,-73.988050,40.763605,-73.989180,member
2,D4E9E27DCE9CC556,classic_bike,2022-09-15 13:25:37,2022-09-15 13:51:35,6 Ave & W 34 St,6364.1,5 Ave & E 78 St,7161.08,40.749640,-73.988050,40.776321,-73.964274,member
3,757BFFFB009E8D21,classic_bike,2022-09-16 18:46:33,2022-09-16 18:52:42,48 St & 5 Ave,3202.06,36 St & 4 Ave,3420.01,40.646351,-74.009271,40.654144,-74.004220,member
4,4E6360AD2986736E,classic_bike,2022-09-10 09:20:56,2022-09-10 09:30:20,Steinway St & Ditmars Blvd,7074.01,Crescent St & 30 Ave,6958.06,40.772621,-73.906240,40.768692,-73.924957,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3507118,991C19F915D01AD4,classic_bike,2022-09-01 09:19:01,2022-09-01 09:42:30,N 15 St & Wythe Ave,5520.09,Lafayette St & E 8 St,5788.13,40.724055,-73.955736,40.730207,-73.991026,member
3507119,B1C2E48F72C8EC15,classic_bike,2022-09-17 15:21:43,2022-09-17 15:59:19,Greenwich St & Perry St,5922.04,Christopher St & Greenwich St,5847.01,40.734980,-74.006970,40.732916,-74.007114,member
3507120,FA6C91DFB348AABA,classic_bike,2022-09-02 15:09:15,2022-09-02 15:11:48,Southern Blvd & E 172 St,8129.02,Freeman St & Southern Blvd,8060.01,40.834124,-73.889550,40.830051,-73.892103,member
3507121,D3C3E8ADF4F913E3,classic_bike,2022-09-24 01:30:53,2022-09-24 01:35:07,5 Ave & E 29 St,6248.06,E 26 St & 3 Ave,6089.11,40.745168,-73.986831,40.740693,-73.981606,member
3507122,83F64750663161E5,classic_bike,2022-09-20 21:23:46,2022-09-20 21:33:12,Mott St & Prince St,5561.04,Lafayette St & E 8 St,5788.13,40.723180,-73.994800,40.730207,-73.991026,member

In [6]:
# Importing dataframe dated 08/22 for nyc

nyc_bikes_202208 = pd.read_csv(os.path.join(path, 'Downloads', '202208-citibike-tripdata.csv'), index_col = False)
nyc_bikes_202208

/Users/matthewabrams/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (5,7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,428051654CF1145B,classic_bike,2022-08-28 00:34:58,2022-08-28 00:55:20,Walker St & Baxter St,5351.07,Lexington Ave & E 24 St,6089.07,40.717411,-73.999573,40.740259,-73.984092,member
1,7282036E3ECDDD65,classic_bike,2022-08-31 16:33:38,2022-08-31 16:35:17,Lexington Ave & E 29 St,6164.09,Lexington Ave & E 24 St,6089.07,40.743116,-73.982154,40.740259,-73.984092,member
2,375C59BE1271E31C,electric_bike,2022-08-27 23:22:10,2022-08-27 23:34:57,E 132 St & Madison Ave,7748.02,Melrose Ave & E 150 St,7879.01,40.810224,-73.937195,40.816827,-73.917338,member
3,7281A7F21CE571AF,classic_bike,2022-08-26 19:01:01,2022-08-26 19:09:26,Lexington Ave & E 29 St,6164.09,E 13 St & 2 Ave,5820.08,40.743116,-73.982154,40.731539,-73.985302,member
4,A5093D7D77713F87,classic_bike,2022-08-25 22:16:16,2022-08-25 22:29:13,E 16 St & Irving Pl,5938.11,W 31 St & 7 Ave,6331.01,40.735367,-73.987974,40.749156,-73.991600,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3681304,231398EE256269B0,classic_bike,2022-08-17 17:48:50,2022-08-17 18:06:13,27 St & Hunter St,6310.06,E 54 St & 1 Ave,6608.09,40.748500,-73.941275,40.756265,-73.964179,member
3681305,2F9EC3A7F60523B1,classic_bike,2022-08-08 23:02:58,2022-08-08 23:19:10,W 22 St & 10 Ave,6306.06,W 15 St & 6 Ave,5989.02,40.746920,-74.004519,40.738046,-73.996430,member
3681306,094B17D42252E33E,classic_bike,2022-08-27 11:10:59,2022-08-27 11:14:03,27 St & Hunter St,6310.06,11 St & 43 Ave,6438.04,40.748500,-73.941275,40.751907,-73.947912,member
3681307,9CEB6714CBEC7386,classic_bike,2022-08-29 22:55:27,2022-08-29 23:13:10,Washington Pl & Broadway,5755.01,Canal St & Rutgers St,5303.08,40.729039,-73.994046,40.714275,-73.989900,member
3681308,6F9ADF0B11F82DBE,classic_bike,2022-08-29 13:00:22,2022-08-29 13:10:08,Washington Pl & Broadway,5755.01,Canal St & Rutgers St,5303.08,40.729039,-73.994046,40.714275,-73.989900,member

In [7]:
# Importing dataframe dated 07/22 for nyc

nyc_bikes_202207 = pd.read_csv(os.path.join(path, 'Downloads', '202207-citbike-tripdata.csv'), index_col = False)
nyc_bikes_202207

/Users/matthewabrams/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (5,7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,C09E4093905089BD,classic_bike,2022-07-23 11:34:57,2022-07-23 11:45:08,Melrose St & Broadway,4801.04,Myrtle Ave & Grove St,4816.05,40.697481,-73.935877,40.699050,-73.915160,member
1,374630DB5822C392,electric_bike,2022-07-29 18:19:08,2022-07-29 18:26:50,E 68 St & 3 Ave,6896.16,E 85 St & York Ave,7146.04,40.767128,-73.962246,40.775369,-73.948034,member
2,4F73CA25880A1215,electric_bike,2022-07-16 16:30:58,2022-07-16 17:39:18,W 37 St & 10 Ave,6611.02,Knickerbocker Ave & Cooper St,4582.05,40.756604,-73.997901,40.690810,-73.904480,member
3,ECD6EE19C0CC1D31,electric_bike,2022-07-17 17:35:57,2022-07-17 18:03:36,W 37 St & 10 Ave,6611.02,6 Ave & Broome St,5610.09,40.756604,-73.997901,40.724310,-74.004730,member
4,44D0987673B9997D,classic_bike,2022-07-11 07:56:29,2022-07-11 07:59:15,E 68 St & 3 Ave,6896.16,E 66 St & Madison Ave,6969.08,40.767128,-73.962246,40.768009,-73.968453,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3497385,EF571F06A5E34311,docked_bike,2022-07-10 14:08:11,2022-07-10 14:36:45,W 106 St & Central Park West,7606.01,Grand Army Plaza & Central Park S,6839.1,40.798186,-73.960591,40.764397,-73.973715,casual
3497386,9F9F55113999F07B,electric_bike,2022-07-27 01:47:52,2022-07-27 02:11:40,Delancey St & Eldridge St,5414.07,Calyer St & Guernsey St,5709.03,40.719383,-73.991479,40.727558,-73.955059,member
3497387,CBB7EF472D45EDAD,classic_bike,2022-07-18 19:35:34,2022-07-18 19:57:15,Grand Concourse & East Mount Eden Ave,8265.09,Weeks Ave & E 175 St,8340.05,40.843043,-73.911753,40.846879,-73.907342,member
3497388,C2176A140EBE4FB5,classic_bike,2022-07-25 08:13:04,2022-07-25 08:58:29,Court St & State St,4488.08,E 53 St & Lexington Ave,6617.09,40.690147,-73.992072,40.758281,-73.970694,member
3497389,405C56C8930284FD,classic_bike,2022-07-08 12:18:47,2022-07-08 12:27:02,W 59 St & 10 Ave,7023.04,Grand Army Plaza & Central Park S,6839.1,40.770513,-73.988038,40.764397,-73.973715,member

In [8]:
# Importing dataframe dated 06/22 for nyc

nyc_bikes_202206 = pd.read_csv(os.path.join(path, 'Downloads', '202206-citbike-tripdata.csv'), index_col = False)
nyc_bikes_202206

/Users/matthewabrams/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (5,7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,FD85DE523427365B,classic_bike,2022-06-08 18:55:00,2022-06-08 18:58:13,E 149 St & Park Ave,7884.04,Morris Ave & E 153 St,7901.04,40.818154,-73.925294,40.820036,-73.921411,member
1,E1DF44B06B360036,classic_bike,2022-06-18 16:34:50,2022-06-18 16:47:49,E 115 St & Madison Ave,7599.02,W 148 St & Amsterdam Ave,8033.09,40.798983,-73.944716,40.827075,-73.945909,member
2,72B6DBF42BC1F9E1,classic_bike,2022-06-11 17:57:00,2022-06-11 18:07:33,E 115 St & Madison Ave,7599.02,2 Ave & E 99 St,7386.10,40.798944,-73.944846,40.786259,-73.945526,member
3,5FABA5CB97A6EA64,classic_bike,2022-06-23 17:32:04,2022-06-23 17:38:36,W Broadway & Spring St,5569.06,N Moore St & Hudson St,5470.02,40.724947,-74.001659,40.719961,-74.008443,member
4,EBA54764AA1A3A41,classic_bike,2022-06-30 16:17:43,2022-06-30 16:27:58,E 14 St & 1 Ave,5779.1,5 Ave & E 29 St,6248.06,40.731393,-73.982867,40.745168,-73.986831,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3432878,52758C21D58728B4,classic_bike,2022-06-25 00:45:19,2022-06-25 00:58:01,Norman St & Wyckoff Ave,4654.01,Grove St & Broadway,4526.01,40.695170,-73.903110,40.690470,-73.923511,casual
3432879,2F2B099B77266BF2,classic_bike,2022-06-21 16:52:08,2022-06-21 17:16:43,Railroad Ave & Kay Ave,4990.02,Grove St & Broadway,4526.01,40.705148,-73.970781,40.690470,-73.923511,member
3432880,AEE172A41A2FDA65,classic_bike,2022-06-29 17:58:20,2022-06-29 18:12:10,Bushwick Ave & Powers St,5250.05,S 4 St & Wythe Ave,5204.05,40.712477,-73.941000,40.712859,-73.965903,member
3432881,3E6A2E15FD49F94E,classic_bike,2022-06-16 19:31:34,2022-06-16 19:42:42,Bushwick Ave & Powers St,5250.05,S 4 St & Wythe Ave,5204.05,40.712477,-73.941000,40.712859,-73.965903,member
3432882,EA18E4BF86FD46F8,classic_bike,2022-06-16 12:15:02,2022-06-16 12:16:40,Broadway & W 51 St,6779.04,8 Ave & W 49 St,6747.07,40.762288,-73.983362,40.761712,-73.986551,member

In [9]:
# Importing dataframe dated 05/22 for nyc

nyc_bikes_202205 = pd.read_csv(os.path.join(path, 'Downloads', '202205-citibike-tripdata.csv'), index_col = False)
nyc_bikes_202205

/Users/matthewabrams/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (5,7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,F49280E52B6491D8,electric_bike,2022-05-16 16:58:35,2022-05-16 17:08:56,Central Park North & Adam Clayton Powell Blvd,7617.07,E 89 St & 3 Ave,7265.10,40.799484,-73.955613,40.780628,-73.952167,member
1,B587F12BCC6778B0,electric_bike,2022-05-19 17:41:41,2022-05-19 17:53:35,Broadway & E 19 St,6098.12,W 44 St & 5 Ave,6551.02,40.738661,-73.989873,40.755003,-73.980144,member
2,D89D4D15B4E42A23,classic_bike,2022-05-27 08:34:05,2022-05-27 08:37:38,Rockaway Ave & Bainbridge St,4285.09,Van Sinderen Ave & Truxton St,4161.01,40.683200,-73.911666,40.678600,-73.903690,member
3,94B921DF9913EB66,electric_bike,2022-05-13 22:25:06,2022-05-13 22:51:29,Lexington Ave & E 36 St,6313.10,Grand St & Havemeyer St,5267.08,40.747574,-73.978801,40.712868,-73.956981,member
4,B81A75AC39BA13E1,classic_bike,2022-05-13 09:16:56,2022-05-13 09:24:25,Willoughby Ave & Hall St,4611.03,Bond St & Fulton St,4479.06,40.691960,-73.965369,40.689622,-73.983043,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2940595,6F515775CE3012B9,classic_bike,2022-05-15 07:57:48,2022-05-15 08:12:55,Broadway & W 36 St,6441.01,West End Ave & W 60 St,7059.08,40.750977,-73.987654,40.772370,-73.990050,member
2940596,25F899C46BB26C7D,classic_bike,2022-05-05 18:13:05,2022-05-05 18:20:10,Crescent St & 30 Ave,6958.06,Vernon Blvd & 31 Ave,7003.06,40.768692,-73.924957,40.769247,-73.935450,member
2940597,E9C36AD563030276,classic_bike,2022-05-28 00:12:09,2022-05-28 00:30:00,45 Ave & 21 St,6319.07,Vernon Blvd & 31 Ave,7003.06,40.747371,-73.947773,40.769247,-73.935450,member
2940598,27FA793948D2916A,classic_bike,2022-05-19 13:06:36,2022-05-19 13:18:02,Crescent St & 30 Ave,6958.06,46 St & 28 Ave,6842.02,40.768692,-73.924957,40.763328,-73.908782,member
2940599,7452B0859F68D412,classic_bike,2022-05-09 18:47:28,2022-05-09 18:52:38,W 50 St & 9 Ave,6854.05,West End Ave & W 60 St,7059.08,40.763605,-73.989180,40.772370,-73.990050,member

In [10]:
# Importing dataframe dated 04/22 for nyc

nyc_bikes_202204 = pd.read_csv(os.path.join(path, 'Downloads', '202204-citibike-tripdata.csv'), index_col = False)
nyc_bikes_202204

/Users/matthewabrams/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (5,7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,2E89F1D88B8347E6,classic_bike,2022-04-08 19:50:00,2022-04-08 19:55:28,E 89 St & 3 Ave,7265.10,Madison Ave & E 99 St,7443.01,40.780628,-73.952167,40.789485,-73.952429,member
1,43F6D61DFEDAE4AF,electric_bike,2022-04-27 10:19:54,2022-04-27 10:33:29,Broadway & W 29 St,6289.06,Broadway & W 29 St,6289.06,40.746201,-73.988557,40.746201,-73.988557,member
2,21C7076071104314,classic_bike,2022-04-28 13:10:59,2022-04-28 13:17:18,E 123 St & Lexington Ave,7636.05,E 123 St & Lexington Ave,7636.05,40.802926,-73.937900,40.802926,-73.937900,member
3,7D7CEA2953427D0C,classic_bike,2022-04-13 20:21:18,2022-04-13 20:37:28,W 36 St & 9 Ave,6569.07,W 36 St & 9 Ave,6569.07,40.754623,-73.995168,40.754623,-73.995168,member
4,AD7E176748A4A55E,electric_bike,2022-04-29 18:56:24,2022-04-29 18:57:16,Graham Ave & Withers St,5403.04,Graham Ave & Withers St,5403.04,40.716981,-73.944859,40.716981,-73.944859,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2319608,5EBE9D296B9D3E3C,classic_bike,2022-04-22 13:08:15,2022-04-22 13:29:31,Allen St & Rivington St,5414.06,W 29 St & 9 Ave,6416.06,40.720196,-73.989978,40.750073,-73.998393,member
2319609,B66382DEDA84C464,classic_bike,2022-04-13 17:10:49,2022-04-13 17:26:08,St. Nicholas Terrace & Convent Ave,7937.15,E 138 St & Grand Concourse,7803.08,40.821294,-73.947868,40.813224,-73.930605,member
2319610,9EC4C49BE4CB1A09,classic_bike,2022-04-12 15:58:47,2022-04-12 16:41:17,E 88 St & 1 Ave,7235.13,E 91 St & 2 Ave,7286.01,40.778301,-73.948813,40.781153,-73.949630,member
2319611,C0188AB9FAEAA143,electric_bike,2022-04-28 15:52:49,2022-04-28 16:06:31,W 55 St & 6 Ave,6809.09,E 91 St & 2 Ave,7286.01,40.763189,-73.978434,40.781153,-73.949630,member
2319612,E8C2F305866DF134,electric_bike,2022-04-11 19:55:31,2022-04-11 20:09:19,W 87 St & West End Ave,7484.05,E 91 St & 2 Ave,7286.01,40.789622,-73.977570,40.781153,-73.949630,member

In [11]:
# Importing dataframe dated 03/22 for nyc

nyc_bikes_202203 = pd.read_csv(os.path.join(path, 'Downloads', '202203-citibike-tripdata.csv'), index_col = False)
nyc_bikes_202203

/Users/matthewabrams/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (5,7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,FA2F660C8D433037,electric_bike,2022-03-04 18:58:36,2022-03-04 19:13:51,Washington St & Barrow St,5847.08,University Pl & E 14 St,5905.14,40.731911,-74.008769,40.734814,-73.992085,member
1,03B6FE6FAEE61465,classic_bike,2022-03-06 20:37:09,2022-03-06 20:45:28,Washington St & Barrow St,5847.08,W 11 St & 6 Ave,5914.03,40.731911,-74.008769,40.735324,-73.998004,member
2,6E6995761B4A5760,classic_bike,2022-03-01 15:13:49,2022-03-01 15:19:53,1 Ave & E 110 St,7522.02,E 110 St & Madison Ave,7587.14,40.792327,-73.938300,40.796154,-73.947821,member
3,AA51CCF6CEDD6033,classic_bike,2022-03-11 13:59:03,2022-03-11 14:06:43,Crescent St & Broadway,6827.11,31 Rd & 21 St,6929.02,40.763359,-73.928647,40.766824,-73.930486,member
4,72AA3A7D430D8EF8,classic_bike,2022-03-08 14:59:16,2022-03-08 15:05:04,Crescent St & Broadway,6827.11,31 Rd & 21 St,6929.02,40.763359,-73.928647,40.766824,-73.930486,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1893439,79E49EA8727CA662,classic_bike,2022-03-30 21:12:45,2022-03-30 21:22:15,E 72 St & York Ave,6889.12,E 58 St & 3 Ave,6762.02,40.766638,-73.953483,40.760958,-73.967245,member
1893440,9C4F6A095779AAE2,electric_bike,2022-03-21 09:33:21,2022-03-21 09:39:45,W 48 St & Rockefeller Plaza,6626.11,E 58 St & 3 Ave,6762.02,40.757769,-73.979294,40.760958,-73.967245,member
1893441,C1966A89B5078124,electric_bike,2022-03-04 14:31:36,2022-03-04 14:43:16,Central Park West & W 85 St,7354.01,E 58 St & 3 Ave,6762.02,40.784760,-73.969862,40.760958,-73.967245,member
1893442,A11D1F167EF1B8C6,classic_bike,2022-03-18 18:43:43,2022-03-18 18:53:41,W 56 St & 6 Ave,6809.07,E 58 St & 3 Ave,6762.02,40.763406,-73.977225,40.760958,-73.967245,member
1893443,74A6A40E386BE88F,electric_bike,2022-03-10 17:21:52,2022-03-10 17:29:53,5 Ave & E 72 St,7100.07,E 58 St & 3 Ave,6762.02,40.772828,-73.966853,40.760958,-73.967245,casual

In [12]:
# Importing dataframe dated 02/22 for nyc

nyc_bikes_202202 = pd.read_csv(os.path.join(path, 'Downloads', '202202-citibike-tripdata.csv'), index_col = False)
nyc_bikes_202202

/Users/matthewabrams/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (5,7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,6C29577D0141AACD,electric_bike,2022-02-27 16:00:58,2022-02-27 16:10:09,Cliff St & Fulton St,5065.14,Norfolk St & Broome St,5374.01,40.708380,-74.004950,40.717227,-73.988021,member
1,353462A61AFB32C8,classic_bike,2022-02-02 18:09:30,2022-02-02 18:28:55,2 Ave & E 31 St,6197.02,Norfolk St & Broome St,5374.01,40.742909,-73.977061,40.717227,-73.988021,member
2,220081222C7CC84D,classic_bike,2022-02-10 19:41:09,2022-02-10 19:46:03,2 Ave & E 31 St,6197.02,5 Ave & E 29 St,6248.06,40.742909,-73.977061,40.745168,-73.986831,member
3,C66CB5EDE74A7404,classic_bike,2022-02-14 15:52:02,2022-02-14 16:01:58,Bridge St & Water St,4968.03,Henry St & Atlantic Ave,4531.05,40.702969,-73.984691,40.690893,-73.996123,member
4,6B997C1E4DCDD6BF,classic_bike,2022-02-23 13:25:07,2022-02-23 15:36:45,Lafayette St & Jersey St,5561.06,Fulton St & Broadway,5175.08,40.724561,-73.995653,40.711066,-74.009447,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1233709,DB7E2CCB36FE2470,classic_bike,2022-02-02 20:20:40,2022-02-02 20:32:36,Columbus Ave & W 95 St,7520.07,E 110 St & Madison Ave,7587.14,40.791956,-73.968087,40.796154,-73.947821,member
1233710,2589BCEF3734CEFA,electric_bike,2022-02-12 18:21:44,2022-02-12 18:30:48,Central Park West & W 85 St,7354.01,E 110 St & Madison Ave,7587.14,40.784760,-73.969862,40.796154,-73.947821,member
1233711,D808B985BB9F9D72,classic_bike,2022-02-26 12:58:46,2022-02-26 13:11:58,Stanton St & Mangin St,5326.06,E 10 St & 2 Ave,5746.02,40.717821,-73.976289,40.729708,-73.986598,casual
1233712,F3CBF555F8561BF0,electric_bike,2022-02-18 11:03:02,2022-02-18 11:06:01,E 11 St & 3 Ave,5788.16,E 10 St & 2 Ave,5746.02,40.731270,-73.988490,40.729708,-73.986598,casual
1233713,2F8F2920C1A9D0E8,electric_bike,2022-02-19 18:11:55,2022-02-19 18:38:39,E 33 St & 5 Ave,6322.01,Mott St & Prince St,5561.04,40.747659,-73.984907,40.723180,-73.994800,casual

In [13]:
# Importing dataframe dated 01/22 for nyc

nyc_bikes_202201 = pd.read_csv(os.path.join(path, 'Downloads', '202201-citibike-tripdata.csv'), index_col = False)
nyc_bikes_202201

/Users/matthewabrams/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (5,7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,40.692395,-73.993379,member
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,40.727408,-73.981420,member
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,40.762009,-73.996975,member
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,40.768692,-73.924957,member
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,40.696233,-73.991421,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1052413,3A8436E896501EB6,classic_bike,2022-01-09 09:40:49,2022-01-09 09:58:55,27 St & Hunter St,6310.06,Vernon Blvd & 50 Ave,6170.02,40.748500,-73.941275,40.742327,-73.954117,casual
1052414,31EE3AF319AE47D2,classic_bike,2022-01-26 16:11:27,2022-01-26 16:17:20,Monroe St & Bedford Ave,4368.05,Putnam Ave & Throop Ave,4392.04,40.685144,-73.953809,40.685153,-73.941110,casual
1052415,C27D809EC458BE2A,electric_bike,2022-01-20 11:39:41,2022-01-20 11:44:46,E 118 St & 1 Ave,7596.1,Lexington Ave & E 111 St,7567.06,40.797470,-73.935040,40.795412,-73.944123,member
1052416,4968572973DEDCB2,electric_bike,2022-01-18 21:17:11,2022-01-18 21:25:57,Allen St & Hester St,5342.1,1 Ave & E 18 St,5854.09,40.716059,-73.991908,40.733812,-73.980544,member
1052417,B40238814400C8B2,classic_bike,2022-01-22 19:05:54,2022-01-22 19:16:39,Gansevoort St & Hudson St,6072.14,12 Ave & W 40 St,6765.01,40.739448,-74.005070,40.760875,-74.002777,member

# 2) Combining Dataframes

In [14]:
# Combining all dataframes for nyc using concat method

frames = [nyc_bikes_202201, nyc_bikes_202202, nyc_bikes_202203, nyc_bikes_202204, 
          nyc_bikes_202205, nyc_bikes_202206, nyc_bikes_202207, nyc_bikes_202208, nyc_bikes_202209,
          nyc_bikes_202210, nyc_bikes_202211, nyc_bikes_202212]
nyc_bikes = pd.concat(frames, axis = 0)
nyc_bikes

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,40.692395,-73.993379,member
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,40.727408,-73.981420,member
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,40.762009,-73.996975,member
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,40.768692,-73.924957,member
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,40.696233,-73.991421,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1649647,CB2EE50F60A58C7B,classic_bike,2022-12-12 08:38:46,2022-12-12 08:46:12,E 41 St & Madison Ave (SW corner),6474.12,6 Ave & W 33 St,6364.07,40.752165,-73.979922,40.749013,-73.988484,member
1649648,3C0DF3280FEB1350,classic_bike,2022-12-12 13:06:32,2022-12-12 13:19:58,Peck Slip & South St,5096.12,Vesey St & Church St,5216.06,40.707689,-74.001254,40.712220,-74.010472,member
1649649,B916E63B630D5020,classic_bike,2022-12-18 01:15:22,2022-12-18 01:48:15,E 41 St & Madison Ave (SW corner),6474.12,Lenox Ave & W 111 St,7602.05,40.752399,-73.980150,40.798786,-73.952300,member
1649650,21EAC007BE7D4161,classic_bike,2022-12-08 23:09:54,2022-12-08 23:26:37,W 37 St & 10 Ave,6611.02,W 70 St & Amsterdam Ave,7207.08,40.756604,-73.997901,40.777480,-73.982886,member
1649651,538408C4A16F4415,electric_bike,2022-12-21 07:26:14,2022-12-21 07:31:40,W 37 St & 10 Ave,6611.02,6 Ave & W 33 St,6364.07,40.756604,-73.997901,40.749013,-73.988484,member

# 3) Checking for missing values, duplicates, and inconsistant values

In [15]:
# Checking for null values

nyc_bikes.isnull().sum()

ride_id                   0
rideable_type             0
started_at                0
ended_at                  0
start_station_name       50
start_station_id         50
end_station_name      71773
end_station_id        71773
start_lat                 0
start_lng                 0
end_lat               37516
end_lng               37516
member_casual             0
dtype: int64

In [16]:
# Dropping null values under'start_station_name','end_station_name'
# Want to return all known values for where people bike from and where to

nyc_bikes.dropna(subset = ['start_station_name','end_station_name'], inplace = True)
nyc_bikes

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,40.692395,-73.993379,member
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,40.727408,-73.981420,member
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,40.762009,-73.996975,member
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,40.768692,-73.924957,member
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,40.696233,-73.991421,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1649647,CB2EE50F60A58C7B,classic_bike,2022-12-12 08:38:46,2022-12-12 08:46:12,E 41 St & Madison Ave (SW corner),6474.12,6 Ave & W 33 St,6364.07,40.752165,-73.979922,40.749013,-73.988484,member
1649648,3C0DF3280FEB1350,classic_bike,2022-12-12 13:06:32,2022-12-12 13:19:58,Peck Slip & South St,5096.12,Vesey St & Church St,5216.06,40.707689,-74.001254,40.712220,-74.010472,member
1649649,B916E63B630D5020,classic_bike,2022-12-18 01:15:22,2022-12-18 01:48:15,E 41 St & Madison Ave (SW corner),6474.12,Lenox Ave & W 111 St,7602.05,40.752399,-73.980150,40.798786,-73.952300,member
1649650,21EAC007BE7D4161,classic_bike,2022-12-08 23:09:54,2022-12-08 23:26:37,W 37 St & 10 Ave,6611.02,W 70 St & Amsterdam Ave,7207.08,40.756604,-73.997901,40.777480,-73.982886,member
1649651,538408C4A16F4415,electric_bike,2022-12-21 07:26:14,2022-12-21 07:31:40,W 37 St & 10 Ave,6611.02,6 Ave & W 33 St,6364.07,40.756604,-73.997901,40.749013,-73.988484,member

In [17]:
# Checking for duplicates
# No duplicates

nyc_bikes[nyc_bikes.duplicated()]

Empty DataFrame
Columns: [ride_id, rideable_type, started_at, ended_at, start_station_name, start_station_id, end_station_name, end_station_id, start_lat, start_lng, end_lat, end_lng, member_casual]
Index: []

In [18]:
nyc_bikes['start_station_name'].value_counts()

W 21 St & 6 Ave                   131483
West St & Chambers St             126041
Broadway & W 58 St                117529
6 Ave & W 33 St                   109334
1 Ave & E 68 St                   108240
                                   ...
Lexington Ave & Stuyvesant Ave         9
W 40 St & 8 Ave                        8
E 6 St 2 Ave                           7
Sharon St & Olive St_new               4
Schermerhorn St and Court St           2
Name: start_station_name, Length: 1761, dtype: int64

In [19]:
nyc_bikes['end_station_name'].value_counts()

W 21 St & 6 Ave                               132828
West St & Chambers St                         127329
Broadway & W 58 St                            113526
1 Ave & E 68 St                               108678
6 Ave & W 33 St                               107649
                                               ...
Apache                                             1
Hoboken Ave at Monmouth St                         1
Clinton St & 7 St                                  1
Southwest Park - Jackson St & Observer Hwy         1
7 Ave & Bleecker St                                1
Name: end_station_name, Length: 1841, dtype: int64

In [20]:
# Finding how many types of ridable bikes there are
# There are three types of rideable bikes

nyc_bikes['rideable_type'].unique()

array(['classic_bike', 'electric_bike', 'docked_bike'], dtype=object)

In [21]:
nyc_bikes['member_casual'].unique()

array(['member', 'casual'], dtype=object)

# 4) Changing datatypes and adding new columns

In [22]:
# Changing datatype of column from object to datestamp

nyc_bikes['started_at'] = pd.to_datetime(nyc_bikes['started_at'])

In [23]:
# Changing datatype of column from object to datestamp

nyc_bikes['ended_at'] = pd.to_datetime(nyc_bikes['ended_at'])

In [24]:
# Checking for changes made in datatypes of each column

nyc_bikes.dtypes

ride_id                       object
rideable_type                 object
started_at            datetime64[ns]
ended_at              datetime64[ns]
start_station_name            object
start_station_id              object
end_station_name              object
end_station_id                object
start_lat                    float64
start_lng                    float64
end_lat                      float64
end_lng                      float64
member_casual                 object
dtype: object

In [25]:
# Creating column for how much time spent on bike ride, labeled "time_spent_with_bike"
# Formula was derived from taking the difference between "ended_at" and "started_at" column

nyc_bikes["time_spent_with_bike"] = nyc_bikes['ended_at'] - nyc_bikes['started_at']
nyc_bikes

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,time_spent_with_bike
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,40.692395,-73.993379,member,0 days 00:04:26
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,40.727408,-73.981420,member,0 days 00:02:22
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,40.762009,-73.996975,member,0 days 00:24:46
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,40.768692,-73.924957,member,0 days 00:04:15
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,40.696233,-73.991421,member,0 days 00:08:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1649647,CB2EE50F60A58C7B,classic_bike,2022-12-12 08:38:46,2022-12-12 08:46:12,E 41 St & Madison Ave (SW corner),6474.12,6 Ave & W 33 St,6364.07,40.752165,-73.979922,40.749013,-73.988484,member,0 days 00:07:26
1649648,3C0DF3280FEB1350,classic_bike,2022-12-12 13:06:32,2022-12-12 13:19:58,Peck Slip & South St,5096.12,Vesey St & Church St,5216.06,40.707689,-74.001254,40.712220,-74.010472,member,0 days 00:13:26
1649649,B916E63B630D5020,classic_bike,2022-12-18 01:15:22,2022-12-18 01:48:15,E 41 St & Madison Ave (SW corner),6474.12,Lenox Ave & W 111 St,7602.05,40.752399,-73.980150,40.798786,-73.952300,member,0 days 00:32:53
1649650,21EAC007BE7D4161,classic_bike,2022-12-08 23:09:54,2022-12-08 23:26:37,W 37 St & 10 Ave,6611.02,W 70 St & Amsterdam Ave,7207.08,40.756604,-73.997901,40.777480,-73.982886,member,0 days 00:16:43
1649651,538408C4A16F4415,electric_bike,2022-12-21 07:26:14,2022-12-21 07:31:40,W 37 St & 10 Ave,6611.02,6 Ave & W 33 St,6364.07,40.756604,-73.997901,40.749013,-73.988484,member,0 days 00:05:26

In [26]:
# Changed data type of 'time_spent_with_bike' column to an integer and also converted time spent to total seconds

nyc_bikes['time_spent_with_bike'] = nyc_bikes['time_spent_with_bike'].dt.total_seconds().astype(int)
nyc_bikes

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,time_spent_with_bike
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,40.692395,-73.993379,member,266
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,40.727408,-73.981420,member,142
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,40.762009,-73.996975,member,1486
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,40.768692,-73.924957,member,255
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,40.696233,-73.991421,member,480
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1649647,CB2EE50F60A58C7B,classic_bike,2022-12-12 08:38:46,2022-12-12 08:46:12,E 41 St & Madison Ave (SW corner),6474.12,6 Ave & W 33 St,6364.07,40.752165,-73.979922,40.749013,-73.988484,member,446
1649648,3C0DF3280FEB1350,classic_bike,2022-12-12 13:06:32,2022-12-12 13:19:58,Peck Slip & South St,5096.12,Vesey St & Church St,5216.06,40.707689,-74.001254,40.712220,-74.010472,member,806
1649649,B916E63B630D5020,classic_bike,2022-12-18 01:15:22,2022-12-18 01:48:15,E 41 St & Madison Ave (SW corner),6474.12,Lenox Ave & W 111 St,7602.05,40.752399,-73.980150,40.798786,-73.952300,member,1973
1649650,21EAC007BE7D4161,classic_bike,2022-12-08 23:09:54,2022-12-08 23:26:37,W 37 St & 10 Ave,6611.02,W 70 St & Amsterdam Ave,7207.08,40.756604,-73.997901,40.777480,-73.982886,member,1003
1649651,538408C4A16F4415,electric_bike,2022-12-21 07:26:14,2022-12-21 07:31:40,W 37 St & 10 Ave,6611.02,6 Ave & W 33 St,6364.07,40.756604,-73.997901,40.749013,-73.988484,member,326

In [27]:
# Created new column derived from 'time_spent_with_bike'
# Converted time spent from total seconds to minutes (nearest two places after decimal)

nyc_bikes['time_spent_with_bike_in_minutes'] = round((nyc_bikes['time_spent_with_bike']/60),2)
nyc_bikes

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,time_spent_with_bike,time_spent_with_bike_in_minutes
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,40.692395,-73.993379,member,266,4.43
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,40.727408,-73.981420,member,142,2.37
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,40.762009,-73.996975,member,1486,24.77
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,40.768692,-73.924957,member,255,4.25
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,40.696233,-73.991421,member,480,8.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1649647,CB2EE50F60A58C7B,classic_bike,2022-12-12 08:38:46,2022-12-12 08:46:12,E 41 St & Madison Ave (SW corner),6474.12,6 Ave & W 33 St,6364.07,40.752165,-73.979922,40.749013,-73.988484,member,446,7.43
1649648,3C0DF3280FEB1350,classic_bike,2022-12-12 13:06:32,2022-12-12 13:19:58,Peck Slip & South St,5096.12,Vesey St & Church St,5216.06,40.707689,-74.001254,40.712220,-74.010472,member,806,13.43
1649649,B916E63B630D5020,classic_bike,2022-12-18 01:15:22,2022-12-18 01:48:15,E 41 St & Madison Ave (SW corner),6474.12,Lenox Ave & W 111 St,7602.05,40.752399,-73.980150,40.798786,-73.952300,member,1973,32.88
1649650,21EAC007BE7D4161,classic_bike,2022-12-08 23:09:54,2022-12-08 23:26:37,W 37 St & 10 Ave,6611.02,W 70 St & Amsterdam Ave,7207.08,40.756604,-73.997901,40.777480,-73.982886,member,1003,16.72
1649651,538408C4A16F4415,electric_bike,2022-12-21 07:26:14,2022-12-21 07:31:40,W 37 St & 10 Ave,6611.02,6 Ave & W 33 St,6364.07,40.756604,-73.997901,40.749013,-73.988484,member,326,5.43

In [28]:
# Created two new columns derived from 'ended_at_day_name', 'started_at_day_name'
# Returned the name of day

nyc_bikes['started_at_day_name'] = nyc_bikes['started_at'].dt.day_name()
nyc_bikes['ended_at_day_name'] = nyc_bikes['ended_at'].dt.day_name()
nyc_bikes

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,time_spent_with_bike,time_spent_with_bike_in_minutes,started_at_day_name,ended_at_day_name
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,40.692395,-73.993379,member,266,4.43,Tuesday,Tuesday
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,40.727408,-73.981420,member,142,2.37,Friday,Friday
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,40.762009,-73.996975,member,1486,24.77,Saturday,Saturday
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,40.768692,-73.924957,member,255,4.25,Wednesday,Wednesday
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,40.696233,-73.991421,member,480,8.00,Sunday,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1649647,CB2EE50F60A58C7B,classic_bike,2022-12-12 08:38:46,2022-12-12 08:46:12,E 41 St & Madison Ave (SW corner),6474.12,6 Ave & W 33 St,6364.07,40.752165,-73.979922,40.749013,-73.988484,member,446,7.43,Monday,Monday
1649648,3C0DF3280FEB1350,classic_bike,2022-12-12 13:06:32,2022-12-12 13:19:58,Peck Slip & South St,5096.12,Vesey St & Church St,5216.06,40.707689,-74.001254,40.712220,-74.010472,member,806,13.43,Monday,Monday
1649649,B916E63B630D5020,classic_bike,2022-12-18 01:15:22,2022-12-18 01:48:15,E 41 St & Madison Ave (SW corner),6474.12,Lenox Ave & W 111 St,7602.05,40.752399,-73.980150,40.798786,-73.952300,member,1973,32.88,Sunday,Sunday
1649650,21EAC007BE7D4161,classic_bike,2022-12-08 23:09:54,2022-12-08 23:26:37,W 37 St & 10 Ave,6611.02,W 70 St & Amsterdam Ave,7207.08,40.756604,-73.997901,40.777480,-73.982886,member,1003,16.72,Thursday,Thursday
1649651,538408C4A16F4415,electric_bike,2022-12-21 07:26:14,2022-12-21 07:31:40,W 37 St & 10 Ave,6611.02,6 Ave & W 33 St,6364.07,40.756604,-73.997901,40.749013,-73.988484,member,326,5.43,Wednesday,Wednesday

In [29]:
# Created two new columns derived from 'ended_at_day_name', 'started_at_day_name'
# Returned the hour of day

nyc_bikes['started_at_hour'] = nyc_bikes['started_at'].dt.hour
nyc_bikes['ended_at_hour'] = nyc_bikes['ended_at'].dt.hour
nyc_bikes

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,time_spent_with_bike,time_spent_with_bike_in_minutes,started_at_day_name,ended_at_day_name,started_at_hour,ended_at_hour
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,40.692395,-73.993379,member,266,4.43,Tuesday,Tuesday,8,8
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,40.727408,-73.981420,member,142,2.37,Friday,Friday,9,9
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,40.762009,-73.996975,member,1486,24.77,Saturday,Saturday,14,14
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,40.768692,-73.924957,member,255,4.25,Wednesday,Wednesday,14,14
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,40.696233,-73.991421,member,480,8.00,Sunday,Sunday,14,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1649647,CB2EE50F60A58C7B,classic_bike,2022-12-12 08:38:46,2022-12-12 08:46:12,E 41 St & Madison Ave (SW corner),6474.12,6 Ave & W 33 St,6364.07,40.752165,-73.979922,40.749013,-73.988484,member,446,7.43,Monday,Monday,8,8
1649648,3C0DF3280FEB1350,classic_bike,2022-12-12 13:06:32,2022-12-12 13:19:58,Peck Slip & South St,5096.12,Vesey St & Church St,5216.06,40.707689,-74.001254,40.712220,-74.010472,member,806,13.43,Monday,Monday,13,13
1649649,B916E63B630D5020,classic_bike,2022-12-18 01:15:22,2022-12-18 01:48:15,E 41 St & Madison Ave (SW corner),6474.12,Lenox Ave & W 111 St,7602.05,40.752399,-73.980150,40.798786,-73.952300,member,1973,32.88,Sunday,Sunday,1,1
1649650,21EAC007BE7D4161,classic_bike,2022-12-08 23:09:54,2022-12-08 23:26:37,W 37 St & 10 Ave,6611.02,W 70 St & Amsterdam Ave,7207.08,40.756604,-73.997901,40.777480,-73.982886,member,1003,16.72,Thursday,Thursday,23,23
1649651,538408C4A16F4415,electric_bike,2022-12-21 07:26:14,2022-12-21 07:31:40,W 37 St & 10 Ave,6611.02,6 Ave & W 33 St,6364.07,40.756604,-73.997901,40.749013,-73.988484,member,326,5.43,Wednesday,Wednesday,7,7

In [30]:
# Created two new columns derived from 'ended_at_day_name', 'started_at_day_name'
# Returned the month of year

nyc_bikes['started_at_month_name'] = nyc_bikes['started_at'].dt.month_name()
nyc_bikes['ended_at_month_name'] = nyc_bikes['ended_at'].dt.month_name()

nyc_bikes

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,end_lng,member_casual,time_spent_with_bike,time_spent_with_bike_in_minutes,started_at_day_name,ended_at_day_name,started_at_hour,ended_at_hour,started_at_month_name,ended_at_month_name
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,...,-73.993379,member,266,4.43,Tuesday,Tuesday,8,8,January,January
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,...,-73.981420,member,142,2.37,Friday,Friday,9,9,January,January
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,...,-73.996975,member,1486,24.77,Saturday,Saturday,14,14,January,January
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,...,-73.924957,member,255,4.25,Wednesday,Wednesday,14,14,January,January
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,...,-73.991421,member,480,8.00,Sunday,Sunday,14,14,January,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1649647,CB2EE50F60A58C7B,classic_bike,2022-12-12 08:38:46,2022-12-12 08:46:12,E 41 St & Madison Ave (SW corner),6474.12,6 Ave & W 33 St,6364.07,40.752165,-73.979922,...,-73.988484,member,446,7.43,Monday,Monday,8,8,December,December
1649648,3C0DF3280FEB1350,classic_bike,2022-12-12 13:06:32,2022-12-12 13:19:58,Peck Slip & South St,5096.12,Vesey St & Church St,5216.06,40.707689,-74.001254,...,-74.010472,member,806,13.43,Monday,Monday,13,13,December,December
1649649,B916E63B630D5020,classic_bike,2022-12-18 01:15:22,2022-12-18 01:48:15,E 41 St & Madison Ave (SW corner),6474.12,Lenox Ave & W 111 St,7602.05,40.752399,-73.980150,...,-73.952300,member,1973,32.88,Sunday,Sunday,1,1,December,December
1649650,21EAC007BE7D4161,classic_bike,2022-12-08 23:09:54,2022-12-08 23:26:37,W 37 St & 10 Ave,6611.02,W 70 St & Amsterdam Ave,7207.08,40.756604,-73.997901,...,-73.982886,member,1003,16.72,Thursday,Thursday,23,23,December,December
1649651,538408C4A16F4415,electric_bike,2022-12-21 07:26:14,2022-12-21 07:31:40,W 37 St & 10 Ave,6611.02,6 Ave & W 33 St,6364.07,40.756604,-73.997901,...,-73.988484,member,326,5.43,Wednesday,Wednesday,7,7,December,December

In [31]:
# Created two new columns derived from 'ended_at_day_name', 'started_at_day_name'
# Returns year

nyc_bikes['started_at_year'] = nyc_bikes['started_at'].dt.year
nyc_bikes['ended_at_year'] = nyc_bikes['ended_at'].dt.year
nyc_bikes

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,time_spent_with_bike,time_spent_with_bike_in_minutes,started_at_day_name,ended_at_day_name,started_at_hour,ended_at_hour,started_at_month_name,ended_at_month_name,started_at_year,ended_at_year
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,...,266,4.43,Tuesday,Tuesday,8,8,January,January,2022,2022
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,...,142,2.37,Friday,Friday,9,9,January,January,2022,2022
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,...,1486,24.77,Saturday,Saturday,14,14,January,January,2022,2022
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,...,255,4.25,Wednesday,Wednesday,14,14,January,January,2022,2022
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,...,480,8.00,Sunday,Sunday,14,14,January,January,2022,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1649647,CB2EE50F60A58C7B,classic_bike,2022-12-12 08:38:46,2022-12-12 08:46:12,E 41 St & Madison Ave (SW corner),6474.12,6 Ave & W 33 St,6364.07,40.752165,-73.979922,...,446,7.43,Monday,Monday,8,8,December,December,2022,2022
1649648,3C0DF3280FEB1350,classic_bike,2022-12-12 13:06:32,2022-12-12 13:19:58,Peck Slip & South St,5096.12,Vesey St & Church St,5216.06,40.707689,-74.001254,...,806,13.43,Monday,Monday,13,13,December,December,2022,2022
1649649,B916E63B630D5020,classic_bike,2022-12-18 01:15:22,2022-12-18 01:48:15,E 41 St & Madison Ave (SW corner),6474.12,Lenox Ave & W 111 St,7602.05,40.752399,-73.980150,...,1973,32.88,Sunday,Sunday,1,1,December,December,2022,2022
1649650,21EAC007BE7D4161,classic_bike,2022-12-08 23:09:54,2022-12-08 23:26:37,W 37 St & 10 Ave,6611.02,W 70 St & Amsterdam Ave,7207.08,40.756604,-73.997901,...,1003,16.72,Thursday,Thursday,23,23,December,December,2022,2022
1649651,538408C4A16F4415,electric_bike,2022-12-21 07:26:14,2022-12-21 07:31:40,W 37 St & 10 Ave,6611.02,6 Ave & W 33 St,6364.07,40.756604,-73.997901,...,326,5.43,Wednesday,Wednesday,7,7,December,December,2022,2022

In [32]:
# Created two new columns derived from 'ended_at_day_name', 'started_at_day_name'
# Returned the year-month-day

nyc_bikes['started_at_date'] = nyc_bikes['started_at'].dt.to_period('D')
nyc_bikes['ended_at_date'] = nyc_bikes['ended_at'].dt.to_period('D')
nyc_bikes

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,started_at_day_name,ended_at_day_name,started_at_hour,ended_at_hour,started_at_month_name,ended_at_month_name,started_at_year,ended_at_year,started_at_date,ended_at_date
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,...,Tuesday,Tuesday,8,8,January,January,2022,2022,2022-01-18,2022-01-18
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,...,Friday,Friday,9,9,January,January,2022,2022,2022-01-21,2022-01-21
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,...,Saturday,Saturday,14,14,January,January,2022,2022,2022-01-22,2022-01-22
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,...,Wednesday,Wednesday,14,14,January,January,2022,2022,2022-01-19,2022-01-19
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,...,Sunday,Sunday,14,14,January,January,2022,2022,2022-01-16,2022-01-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1649647,CB2EE50F60A58C7B,classic_bike,2022-12-12 08:38:46,2022-12-12 08:46:12,E 41 St & Madison Ave (SW corner),6474.12,6 Ave & W 33 St,6364.07,40.752165,-73.979922,...,Monday,Monday,8,8,December,December,2022,2022,2022-12-12,2022-12-12
1649648,3C0DF3280FEB1350,classic_bike,2022-12-12 13:06:32,2022-12-12 13:19:58,Peck Slip & South St,5096.12,Vesey St & Church St,5216.06,40.707689,-74.001254,...,Monday,Monday,13,13,December,December,2022,2022,2022-12-12,2022-12-12
1649649,B916E63B630D5020,classic_bike,2022-12-18 01:15:22,2022-12-18 01:48:15,E 41 St & Madison Ave (SW corner),6474.12,Lenox Ave & W 111 St,7602.05,40.752399,-73.980150,...,Sunday,Sunday,1,1,December,December,2022,2022,2022-12-18,2022-12-18
1649650,21EAC007BE7D4161,classic_bike,2022-12-08 23:09:54,2022-12-08 23:26:37,W 37 St & 10 Ave,6611.02,W 70 St & Amsterdam Ave,7207.08,40.756604,-73.997901,...,Thursday,Thursday,23,23,December,December,2022,2022,2022-12-08,2022-12-08
1649651,538408C4A16F4415,electric_bike,2022-12-21 07:26:14,2022-12-21 07:31:40,W 37 St & 10 Ave,6611.02,6 Ave & W 33 St,6364.07,40.756604,-73.997901,...,Wednesday,Wednesday,7,7,December,December,2022,2022,2022-12-21,2022-12-21

# 5) Filtering out outliers and rides longer than 2 hrs (120 minutes)

In [33]:
# Statistical description of dataframe
# Unusually the bike ride lasts over 50000 minutes
# There is a monetary penalty for rides longer than 45 minutes for members and 30 minutes for casual customers
# It is less likely that any citi bike ride would take several hours
# The System host site indicates that for distance calculation, trips are capped at a 2 hour (120 minutes) limit
# It is highly probable that the bike was not engaged properly at the returning station

nyc_bikes.describe()

,start_lat,start_lng,end_lat,end_lng,time_spent_with_bike,time_spent_with_bike_in_minutes,started_at_hour,ended_at_hour,started_at_year,ended_at_year
count,3.061815e+07,3.061815e+07,3.061815e+07,3.061815e+07,3.061815e+07,3.061815e+07,3.061815e+07,3.061815e+07,30618148.0,3.061815e+07
mean,4.074085e+01,-7.397512e+01,4.074064e+01,-7.397522e+01,9.086554e+02,1.514426e+01,1.406518e+01,1.419205e+01,2022.0,2.022000e+03
std,3.910791e-02,2.595133e-02,3.905234e-02,2.596875e-02,3.650311e+03,6.083852e+01,5.029412e+00,5.094178e+00,0.0,2.549386e-03
min,4.062737e+01,-7.402802e+01,4.063338e+01,-7.408670e+01,-6.780700e+04,-1.130120e+03,0.000000e+00,0.000000e+00,2022.0,2.022000e+03
25%,4.071606e+01,-7.399379e+01,4.071606e+01,-7.399380e+01,3.280000e+02,5.470000e+00,1.000000e+01,1.100000e+01,2022.0,2.022000e+03
50%,4.073945e+01,-7.398163e+01,4.073936e+01,-7.398166e+01,5.900000e+02,9.830000e+00,1.500000e+01,1.500000e+01,2022.0,2.022000e+03
75%,4.076341e+01,-7.395922e+01,4.076319e+01,-7.395922e+01,1.055000e+03,1.758000e+01,1.800000e+01,1.800000e+01,2022.0,2.022000e+03
max,4.088398e+01,-7.387859e+01,4.088226e+01,-7.388145e+01,3.479159e+06,5.798598e+04,2.300000e+01,2.300000e+01,2022.0,2.023000e+03

In [34]:
# We will filter out any trips greater than 2 hours (120 minutes)
nyc_bikes = nyc_bikes[nyc_bikes['time_spent_with_bike_in_minutes']<=120]
nyc_bikes

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,started_at_day_name,ended_at_day_name,started_at_hour,ended_at_hour,started_at_month_name,ended_at_month_name,started_at_year,ended_at_year,started_at_date,ended_at_date
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,...,Tuesday,Tuesday,8,8,January,January,2022,2022,2022-01-18,2022-01-18
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,...,Friday,Friday,9,9,January,January,2022,2022,2022-01-21,2022-01-21
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,...,Saturday,Saturday,14,14,January,January,2022,2022,2022-01-22,2022-01-22
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,...,Wednesday,Wednesday,14,14,January,January,2022,2022,2022-01-19,2022-01-19
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,...,Sunday,Sunday,14,14,January,January,2022,2022,2022-01-16,2022-01-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1649647,CB2EE50F60A58C7B,classic_bike,2022-12-12 08:38:46,2022-12-12 08:46:12,E 41 St & Madison Ave (SW corner),6474.12,6 Ave & W 33 St,6364.07,40.752165,-73.979922,...,Monday,Monday,8,8,December,December,2022,2022,2022-12-12,2022-12-12
1649648,3C0DF3280FEB1350,classic_bike,2022-12-12 13:06:32,2022-12-12 13:19:58,Peck Slip & South St,5096.12,Vesey St & Church St,5216.06,40.707689,-74.001254,...,Monday,Monday,13,13,December,December,2022,2022,2022-12-12,2022-12-12
1649649,B916E63B630D5020,classic_bike,2022-12-18 01:15:22,2022-12-18 01:48:15,E 41 St & Madison Ave (SW corner),6474.12,Lenox Ave & W 111 St,7602.05,40.752399,-73.980150,...,Sunday,Sunday,1,1,December,December,2022,2022,2022-12-18,2022-12-18
1649650,21EAC007BE7D4161,classic_bike,2022-12-08 23:09:54,2022-12-08 23:26:37,W 37 St & 10 Ave,6611.02,W 70 St & Amsterdam Ave,7207.08,40.756604,-73.997901,...,Thursday,Thursday,23,23,December,December,2022,2022,2022-12-08,2022-12-08
1649651,538408C4A16F4415,electric_bike,2022-12-21 07:26:14,2022-12-21 07:31:40,W 37 St & 10 Ave,6611.02,6 Ave & W 33 St,6364.07,40.756604,-73.997901,...,Wednesday,Wednesday,7,7,December,December,2022,2022,2022-12-21,2022-12-21

# 6) Rearranging Columns and Exporting Finalized Dataframe to Desktop

In [35]:
# Returning the name of all columns of dataframe

nyc_bikes.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual', 'time_spent_with_bike',
       'time_spent_with_bike_in_minutes', 'started_at_day_name',
       'ended_at_day_name', 'started_at_hour', 'ended_at_hour',
       'started_at_month_name', 'ended_at_month_name', 'started_at_year',
       'ended_at_year', 'started_at_date', 'ended_at_date'],
      dtype='object')

In [36]:
# Selected and rearranged several columns for dataframe

nyc_bikes = nyc_bikes[['rideable_type', 'member_casual', 'started_at_date', 'started_at_month_name', 'end_station_name', 
                       'end_lat', 'end_lng', 'started_at_day_name', 'started_at_hour', 'time_spent_with_bike_in_minutes']]
nyc_bikes

,rideable_type,member_casual,started_at_date,started_at_month_name,end_station_name,end_lat,end_lng,started_at_day_name,started_at_hour,time_spent_with_bike_in_minutes
0,classic_bike,member,2022-01-18,January,Clinton St & Joralemon St,40.692395,-73.993379,Tuesday,8,4.43
1,classic_bike,member,2022-01-21,January,E 10 St & Avenue A,40.727408,-73.981420,Friday,9,2.37
2,classic_bike,member,2022-01-22,January,W 44 St & 11 Ave,40.762009,-73.996975,Saturday,14,24.77
3,electric_bike,member,2022-01-19,January,Crescent St & 30 Ave,40.768692,-73.924957,Wednesday,14,4.25
4,electric_bike,member,2022-01-16,January,Clinton St & Tillary St,40.696233,-73.991421,Sunday,14,8.00
...,...,...,...,...,...,...,...,...,...,...
1649647,classic_bike,member,2022-12-12,December,6 Ave & W 33 St,40.749013,-73.988484,Monday,8,7.43
1649648,classic_bike,member,2022-12-12,December,Vesey St & Church St,40.712220,-74.010472,Monday,13,13.43
1649649,classic_bike,member,2022-12-18,December,Lenox Ave & W 111 St,40.798786,-73.952300,Sunday,1,32.88
1649650,classic_bike,member,2022-12-08,December,W 70 St & Amsterdam Ave,40.777480,-73.982886,Thursday,23,16.72
1649651,electric_bike,member,2022-12-21,December,6 Ave & W 33 St,40.749013,-73.988484,Wednesday,7,5.43

In [37]:
# Exporting finalized dataframe

nyc_bikes.to_csv(os.path.join(path, 'Desktop', 'bikes_2022.csv'))